### ISSUE TITLE
NoMethodError: undefined method `type' for "VARCHAR2(255)":String

### ISSUE THREAD

**Issue by ChipMaNiAC** [rsim/oracle-enhanced#555] opened 2015-02-18 17:26 UTC
I am using the activerecord-oracle_enhanced-adapter 1.5.5 gem built from the rails42 branch. I cloned the Git repository, checked out the rails42 branch, and built the gem. Bundle shows that I am pointing to the correct gem as well so I don't think the issue is on my end. When I run a Rails migration, this is the output:

```
> bin/rake db:migrate RAILS_ENV=development
rake aborted!
NoMethodError: undefined method `type' for "VARCHAR2(255)":String
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/time_zone_conversion.rb:60:in `create_time_zone_conversion_attribute?'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/time_zone_conversion.rb:49:in `block (2 levels) in inherited'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:61:in `call'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:61:in `block in matching'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:60:in `select'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:60:in `matching'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:56:in `decorators_for'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:47:in `apply'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:28:in `map'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:41:in `find_by_sql'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `map'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:844:in `get_all_versions'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:985:in `migrated'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:990:in `ran?'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `block in runnable'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `reject'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `runnable'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/apps/free/ruby/gems-1501-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/apps/free/ruby/gems-1501-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/apps/free/ruby/gems-1501-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/apps/free/ruby/gems-1501-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/apps/free/ruby/gems-1501-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by yahonda** [comment] 2015-02-18 17:27
Thanks for opening a new one. Please provide the valid migration to reproduce and tell me the ActiveRecord / Rails version you are using, I suppose it is 4.2.0.

**Comment by ChipMaNiAC** [comment] 2015-02-18 17:36
Both are at 4.2.0.

I don't think a migration is causing the issue, but rather line 60 in time_zone_conversion.rb.
```ruby
 57         def create_time_zone_conversion_attribute?(name, cast_type)
 58           time_zone_aware_attributes &&
 59             !self.skip_time_zone_conversion_for_attributes.include?(name.to_sym) &&
 60             (:datetime == cast_type.type)
 61         end
```

**Comment by ChipMaNiAC** [comment] 2015-02-19 22:52
FYI, when just running 'rake db:migrate' this is the output:

```
>  rake db:migrate
rake aborted!
LoadError: cannot load such file -- active_record/connection_adapters/oracle_enhanced_database_tasks.rb
/home/david/.gem/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.5.5/lib/activerecord-oracle_enhanced-adapter.rb:8:in `load'
/home/david/.gem/ruby/2.2.0/gems/activerecord-oracle_enhanced-adapter-1.5.5/lib/activerecord-oracle_enhanced-adapter.rb:8:in `block in <class:OracleEnhancedRailtie>'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:237:in `instance_exec'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:245:in `each'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:245:in `each_registered_block'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:437:in `block in run_tasks_blocks'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/engine/railties.rb:13:in `each'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/engine/railties.rb:13:in `each'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:437:in `run_tasks_blocks'
/apps/free/ruby/gems-1501-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:453:in `load_tasks'
/db/atita/users/dbishai/experimental/asset/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by ChipMaNiAC** [comment] 2015-02-20 19:05
OK so I fixed the issue in the previous post. For some reason my gem build was missing oracle_enhanced_database_tasks.rb in lib/active_record/connection_adapters.

From some digging around I've done, it appears that the original error occurs due to 'type' being deprecated and replaced with 'class'. So 'String'.type is not valid and that is what is causing the error.

**Comment by 9nonnatus** [comment] 2015-02-21 21:31
@ChipMaNiAC anything new you've found on the original issue? I've run into the same error while updating an app to Rails 4.2, but not with oracle-enhanced. It seems like an issue with custom attribute types, but I haven't gotten a chance to dig into it yet. Let me know if you find anything, and I'll do the same.

**Comment by ChipMaNiAC** [comment] 2015-02-21 22:55
It looks like the issue is that the 'type' method has been deprecated and removed and replaced with 'class'. I would assume though that Rails developers knew this and that others would have found this issue much sooner though. So in this case cast_type.type is what is causing the error and should be replaced with cast_type.class. I have created an issue in the Rails project: https://github.com/rails/rails/issues/19028

**Comment by ChipMaNiAC** [comment] 2015-02-21 23:18
Well according to the Rails developers 'type' is a valid method but executing "String".type in the Rails console does not work so I am not sure. I haven't investigated this too closely though so I'll spend some more time on Monday.

**Comment by cyberfox** [comment] 2015-02-24 01:36
First, in a Rails console for a trivial SQLite table:
```
Loading development environment (Rails 4.2.0)
irb(main):001:0> Record.columns[1].cast_type
=> #<ActiveRecord::ConnectionAdapters::SQLite3String:0x007fdd4f5b59d0 @precision=nil, @scale=nil, @limit=nil>
irb(main):002:0> Record.columns[1].cast_type.type
=> :string
```
Next, in a console for a legacy Oracle database:
```
irb(main):061:0> Record.columns[1].cast_type
=> "CHAR(15)"
irb(main):062:0> Record.columns[1].cast_type.type
NoMethodError: undefined method `type' for "CHAR(15)":String
	from (irb):62
	from /usr/bin/irb:12:in `<main>'
```
It looks like the cast_type is not being set correctly in the oracle enhanced adapter.

Hopefully this helps, as I'm running into the same problem, and it's definitely frustrating.

**Comment by 9nonnatus** [comment] 2015-02-24 06:31
Thanks, @cyberfox. Really wish I'd seen your comment before I spent an hour reaching the same conclusion.

**Comment by garyharan** [comment] 2015-02-24 19:31
I'm also experiencing the same issue.  Any way I can help?

**Comment by ChipMaNiAC** [comment] 2015-02-24 20:27
Alright, so I think I got it working. Previously I built the gem from my local git repository and installed it in my home directory. I am using a corporate read only gem installation so any experimental gems I want to try out must be installed locally. I decided to try a different approach where I provide the file path to the git cloned repository in my Gemfile.

In my Gemfile, I now have the following line: 
```ruby
gem 'activerecord-oracle_enhanced-adapter', path: '../oracle-enhanced'
```
This points to a cloned repository of  rsim/oracle-enhanced with the rails42 branch checked out.

Run 'gem list', make sure everything looks OK, then run 'bundle install':

```
> gem list
...
Using activerecord-oracle_enhanced-adapter 1.5.5 from source at ../oracle-enhanced
...
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
>bundle install
```

Now time to test:

```
irb(main):019:0> User.connection_config
=> {:adapter=>"oracle_enhanced", ...}
irb(main):016:0> User.columns[1].cast_type     
=> #<ActiveRecord::Type::String:0x007f87e829c580 @precision=nil, @scale=nil, @limit=255>
irb(main):015:0> User.columns[1].cast_type.type
=> :string
```

So far it seems to be working...

**Comment by yahonda** [comment] 2015-02-25 12:57
@ChipMaNiAC Thanks for the update. I'm closing this issue by using Oracle enhanced adapter at local this issue does not reproduce anymore. If I do not understand it correctly, please reopen this.

@9nonnatus If you have some issues that you reproduce without Oracle enhanced adapter, how about reporting it to Rails issues.

Thanks.

**Closed by yahonda** 2015-02-25 12:57 UTC

**Comment by garyharan** [comment] 2015-02-25 13:43
Thanks for the info.

Once you know which branch it is on you can use bundler's features to checkout a branch of a git repo. This is how I did it:

    gem "activerecord-oracle_enhanced-adapter", git: 'https://github.com/rsim/oracle-enhanced.git', branch: 'rails42'

**Comment by colepanike** [comment] 2015-03-21 02:30
I'm still seeing this issue, it's fixed with the `rails42` branch. When will these changes be made part of the release? I'm a bit concerned that this branch may become unstable unexpectedly. I could do as above and base it on a local git repo, but I'd rather not do that if this is about to be fixed in the master.

**Comment by fruwe** [comment] 2015-12-19 11:52
@colepanike seems to work now, at least with v1.6.5
