### ISSUE TITLE
undefined method `type' for "NUMBER(12)":String 

### ISSUE THREAD

**Issue by Daniel304** [rsim/oracle-enhanced#536] opened 2015-01-15 10:07 UTC
undefined method `type' for "NUMBER(12)":String

**Comment by damau** [comment] 2015-01-15 16:22
I also have this issue.  Or similar:
NoMethodError: undefined method `type' for "VARCHAR2(255)":String

I have used 1.5.1, 1.5.4, 1.5.5
with ruby-oci8 2.1.7
rails 4.2.0
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin11.4.2]

Full stack
NoMethodError: undefined method `type' for "VARCHAR2(255)":String
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/time_zone_conversion.rb:60:in `create_time_zone_conversion_attribute?'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_methods/time_zone_conversion.rb:49:in `block (2 levels) in inherited'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:61:in `call'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:61:in `block in matching'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:60:in `select'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:60:in `matching'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:56:in `decorators_for'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:47:in `apply'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:28:in `map'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:41:in `find_by_sql'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `map'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:844:in `get_all_versions'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:985:in `migrated'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:990:in `ran?'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `block in runnable'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `reject'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:967:in `runnable'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate

**Comment by yahonda** [comment] 2015-01-15 16:45
Would you try `rails42` branch and see if it reproduces.

**Comment by perfectritone** [comment] 2015-01-15 17:44
I had this same issue, and that branch fixed it for me! Great work! Is that branch generally stable?

**Comment by yahonda** [comment] 2015-01-16 00:38
`rails42` is a working branch whose unit test results are `390 examples, 24 failures`.

**Comment by yahonda** [comment] 2015-01-20 21:12
Closing this issue. If it still reproduces please reopen it.

**Closed by yahonda** 2015-01-20 21:12 UTC

**Comment by ChipMaNiAC** [comment] 2015-02-18 17:06
I am using the rails42 branch and I am still facing the same problem as damau.

**Comment by yahonda** [comment] 2015-02-18 17:18
@ChipMaNiAC Would you open another issue/pull request with valid test case since it should be new one and this issue has been closed.

**Comment by yahonda** [comment] 2015-02-18 17:19
Locked this issue.
