### ISSUE TITLE
Uninitialized constant: ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter on tomcat

### ISSUE THREAD

**Issue by swaroopmurthy** [rsim/oracle-enhanced#682] opened 2015-08-05 23:17 UTC
With jruby9000, tomcat wasn't starting up due to the above uninitialized error. Not sure exactly how to reproduce this issue for others, but we were able to fix this by moving up a require line..submitting pull request shortly.

**Comment by yahonda** [comment] 2015-08-10 12:49
Would you show some more detail about the Uninitialized constant to see if your pull request should be merged.

- Was your application running without `Uninitialized constant:` errors using some older version of JRuby, Rails, and/or Oracle enhanced adapter?

- Which kind of changes do you apply, It looks it implies you have upgraded jruby version from some older one to jruby 9.0.0.0 (aka jruby9000).

Thanks.

**Comment by yahonda** [comment] 2015-11-04 14:03
I was trying to reproduce this but not able to reproduce. 

- Here are step by step installation based on https://www.digitalocean.com/community/tutorials/how-to-use-jruby-to-run-a-rails-application-on-apache-tomcat-7-and-ubuntu-14-04

https://gist.github.com/yahonda/64659d2b7b3a86b7b657

Closing this since no feedback yet. Please reopen with steps to reproduce.

**Closed by yahonda** 2015-11-04 14:03 UTC
