### ISSUE TITLE
Error with Rails end_of_* time methods

### ISSUE THREAD

**Issue by TheR2** [rsim/oracle-enhanced#1333] opened 2017-05-10 06:58 UTC
I am moving my app to Rails 5 and got this error in my query.
OCIError: ORA-01830: date format picture ends before converting entire input string: SELECT COUNT(*) FROM "FIN_DOKUMENTI" WHERE (id_pp = '150001967' and konto = '120010' and date >= '2016-12-31 23:00:00' and date <= '2017-12-31 22:59:59.999999')

Ruby code :
date_from = Time.local(2017).beginning_of_year
date_to = Time.local(2017).end_of_year
fin  = FinDokumenti.where("id_pp = ? and konto = '120010' and date >= ? and date <= ?", 
                            @id_pp, date_from, date_to).order(:date)

### Expected behavior
If I look at query that ran OK on older version (v 1.6.9)

SELECT "FIN_DOKUMENTI".* FROM "FIN_DOKUMENTI" WHERE (id_pp = '150001967' and konto = '120010' and date >= TO_DATE('2016-12-31 23:00:00','YYYY-MM-DD HH24:MI:SS') and date <= TO_TIMESTAMP('2017-12-31 22:59:59:000000','YYYY-MM-DD HH24:MI:SS:FF6'))  ORDER BY "FIN_DOKUMENTI"."DATUM_OBDOBJA" ASC

it looks like the problem is in converting date_to to a string.
old (working): 2017-12-31 22:59:59:000000
new(not working): 2017-12-31 22:59:59.999999

Same problem arrises if I use end_of_month. So this might be Rails 5 problem too.

### System configuration
Linux 64 bit.

**Oracle enhanced adapter version**: v 1.7.11

**Ruby version**: 2.3.1p112 

**Oracle Database version**: Oracle Database 11g Release 11.2.0.1.0

by
TheR

**Comment by yahonda** [comment] 2017-05-10 13:57
Thanks for the report.

If your case satisfies all of these cases:

* `FIN_DOKUMENTI` table for `FinDokumenti` model was migrated in Rails 4.2 or earlier
* `date` attribute of `FIN_DOKUMENTI` model was `:datetime` attribute and `date` column type is `DATE`

Please follow this upgrade sections to modify `DATE` column to `TIMESTAMP`.

https://github.com/rsim/oracle-enhanced/blob/master/README.md#upgrade-rails-42-or-older-version-to-rails-5


If it still reproduces after changing `DATE` columns to `TIMESTAMP`,
please create reproduce test case by following https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thanks.

**Comment by TheR2** [comment] 2017-05-11 06:47
Thank you. Problem is that I don't administer that database. I am only collecting some data from its tables. 

Since I am collecting data which belongs to current year I changed the date_to calculation to:
date_to = Time.local(Time.now.year + 1).beginning_of_year

which works as expected.

by
TheR

**Comment by yahonda** [comment] 2017-05-11 23:32
Thanks for the update. Closing since a fix found.

**Closed by yahonda** 2017-05-11 23:32 UTC
