### ISSUE TITLE
rails42: RangeError on query

### ISSUE THREAD

**Issue by wconrad** [rsim/oracle-enhanced#542] opened 2015-01-30 14:09 UTC
When using Rails 4.2 and the rails42 branch of oracle-enhanced, I have a query that dies in ActiveRecord with a RangeError.  This query works under Rails 4.1.9 with oracle-enhanced 1.5.5.

Versions:
* oracle-enhanced, rails42 branch, commit c2d65949799852b85a9479ec75dffeae33bd5bbf
* Rails 4.2.0
* Ruby 2.2.0

The query:

    work_order = 9999999999
    package_filename = "parent_filename"
    Package.
       where(:filename => package_filename,
          "opacs_work_orders.number" => work_order).
      joins(:stuff_group => { :split => {:job => :opacs_work_order}})

The error is:

    RangeError:
      9999999999 is out of range for ActiveRecord::Type::Integer with limit 4

The stack trace is:

```
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:41:in `ensure_in_range'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/type/integer.rb:34:in `cast_value'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/type/value.rb:89:in `type_cast'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/type/numeric.rb:15:in `type_cast'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/quoting.rb:13:in `quote'
/home/wayne/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-e838094abb8f/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:613:in `quote'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:765:in `quote'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:725:in `quoted'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:151:in `visit_Arel_Nodes_Casted'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:13:in `visit'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:675:in `visit_Arel_Nodes_Equality'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:13:in `visit'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:788:in `block in inject_join'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:786:in `each'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:786:in `each_with_index'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:786:in `each'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:786:in `inject'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:786:in `inject_join'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:644:in `visit_Arel_Nodes_And'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:13:in `visit'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:255:in `block in visit_Arel_Nodes_SelectCore'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:254:in `each'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:254:in `each_with_index'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:254:in `visit_Arel_Nodes_SelectCore'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:210:in `block in visit_Arel_Nodes_SelectStatement'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:209:in `each'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:209:in `inject'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/to_sql.rb:209:in `visit_Arel_Nodes_SelectStatement'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/oracle.rb:15:in `visit_Arel_Nodes_SelectStatement'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:13:in `visit'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:7:in `accept'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:487:in `find_take'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:105:in `take'
./app/modules/job_writers/active_record.rb:37:in `add_parent'
./app/modules/job_writers/active_record.rb:29:in `make_job'
./app/modules/job_writers/active_record.rb:17:in `job'
./app/modules/job_writers/active_record.rb:9:in `make_job'
./spec/modules/job_writers/active_record_spec.rb:52:in `block (3 levels) in <module:JobWriters>'
./spec/modules/job_writers/active_record_spec.rb:81:in `block (5 levels) in <module:JobWriters>'
```

The column definition for opacs_work_orders.number is:

    t.integer   "number",                         precision: 38, scale: 0, null: false

# Diving in

The error is raised by ActiveRecord::Type::Integer:

      unless range.cover?(value)
          raise RangeError, "#{value} is out of range for #{self.class} with limit #{limit || 4}"
        end
 
`limit` is nil, so the default of `4` is being used.

The instance of ActiveRecord::Type::Integer is created at oracle_enhanced_adapter.rb:1224:

            Type::Integer.new(precision: precision)

The value of `precision` is 38, as expected.  Limit is not being passed in.

ActiveRecord::Type::Integer#initialize lets its superclass do most of the work:

      def initialize(*)
        super
        @range = min_value...max_value
      end

The superclass is ActiveRecord::Type::Value; its initialize is:

      # Valid options are +precision+, +scale+, and +limit+. They are only
      # used when dumping schema.
      def initialize(options = {})
        options.assert_valid_keys(:precision, :scale, :limit)
        @precision = options[:precision]
        @scale = options[:scale]
        @limit = options[:limit]
      end

The comment says that #limit should only be used when dumping schema.  I'm pretty sure that the query that evokes the stack trace is not dumping schema.

That's as far as I get.  I don't have enough knowledge of active record internals to figure out whether this is an AR bug, and adapter bug, or what.

**Comment by yahonda** [comment] 2015-01-30 14:13
Thanks for the testing and reporting, I think it looks like Oracle enhanced regression not Rails itself. Will take a look at this.

**Comment by wconrad** [comment] 2015-01-30 16:41
You're welcome; thank you for looking at it.  I've not made a minimal program to reproduce this, but will do so if needed.  I'm hoping it won't be needed :)

**Comment by yahonda** [comment] 2015-02-03 15:39
@wconrad Would you try to see if it addresses the `RangeError` by updating your Gemfile?

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'rails42_542' 
```
Note: This fix causes another regression. It needs another fix even if  the `RangeError` is addressed.

**Comment by wconrad** [comment] 2015-02-03 21:21
The rails42_542 branch did address the RangeError.  I understand your warning and won't use that branch.

**Comment by yahonda** [comment] 2015-02-03 21:42
Thanks for the validation. We need to implement `DecimalWithoutScale` type carefully. 

Since [This commit] (https://github.com/yahonda/oracle-enhanced/commit/9fc1081705ab79ef84c124d9c6a162d2df63b723] handles most of `integer` data types as `decimal` which causes some regressions. Will keep working with this.

**Comment by apeiros** [comment] 2015-02-04 15:34
@yahonda what other regression does it introduce? I'd like to evaluate whether the regression is of relevance for my employer.

**Comment by edwagner** [comment] 2015-04-21 16:01
Any idea when the regression might get addressed so that a fix can be merged back into rails42? Or can it be rebased to pick up some of the later fixes? I keep running into this range error.

Thanks for your work on this.

**Comment by yahonda** [comment] 2015-04-22 20:30
#575 has been merged to `rails42` branch, then this issue should be resolved.

**Comment by yahonda** [comment] 2015-04-22 20:31
Closed by mistakes.

**Comment by yahonda** [comment] 2015-04-23 12:49
#578 has been merged to rails42. It should not be fixed.

**Closed by yahonda** 2015-04-23 12:49 UTC
