### ISSUE TITLE
error in db migration when using references

### ISSUE THREAD

**Issue by shannonfuit** [rsim/oracle-enhanced#569] opened 2015-04-02 12:20 UTC
`t.references :outage, index: true, foreign_key: true`
results in error:
>undefined method `add_index' for #><ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000449afa8>

its alias belongs_to works like a charm
 `t.belongs_to :outage, index: true, foreign_key: true`
works like a charm.

full stacktrace:
````
undefined method `add_index' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000449afa8>/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:88:in `block in references_with_foreign_keys'
/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:86:in `each'
/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:86:in `references_with_foreign_keys'
/data/no_tool_dir/na_tool/db/migrate/20150402105314_create_communications.rb:11:in `block in change'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:202:in `create_table'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/data/no_tool_dir/na_tool/db/migrate/20150402105314_create_communications.rb:3:in `change'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `add_index' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000449afa8>
/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:88:in `block in references_with_foreign_keys'
/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:86:in `each'
/home/s-fuit/.rvm/gems/ruby-2.2.0/bundler/gems/oracle-enhanced-6ca7870adaa1/lib/active_record/connection_adapters/oracle_enhanced_schema_definitions.rb:86:in `references_with_foreign_keys'
/data/no_tool_dir/na_tool/db/migrate/20150402105314_create_communications.rb:11:in `block in change'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:202:in `create_table'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/data/no_tool_dir/na_tool/db/migrate/20150402105314_create_communications.rb:3:in `change'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/s-fuit/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
````

**Comment by yahonda** [comment] 2015-04-02 15:40
Would you update if this syntax has been working at Rails 4.1 or lower version of Rails and Oracle enhanced adapter 1.5.5 or lower version?

Since Oracle enhanced adapter has been supporting foreign keys. Then finally Rails 4.2 introduces foreign keys. Unfortunately some of new syntax introduced by Rails 4.2 native foreign key support are not compatible with Oracle enhanced foreign key support.

**Comment by shannonfuit** [comment] 2015-04-03 08:12
the syntax did work for rails <4.1. Seems to be an issue with rails 4.2 specifically.

**Comment by yahonda** [comment] 2015-04-26 18:28
Thanks for the update.

**Comment by yahonda** [comment] 2015-06-20 00:14
Would you try to see if it still reproduces by adding this entry to your Gemfile.
```ruby
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0.beta1" 
```

**Comment by yahonda** [comment] 2015-10-12 12:59
Closing this. Please reopen If it still reproduce using the latest version of Oracle enhanced adapter 1.6.x.

```ruby
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0"
```

**Closed by yahonda** 2015-10-12 12:59 UTC
