### ISSUE TITLE
Please privide Rails 7.1 compatibility

### ISSUE THREAD

**Issue by drgcms** [rsim/oracle-enhanced#2357] opened 2024-01-15 14:13 UTC
### Steps to reproduce
Database connection 

### Expected behavior
Success

### Actual behavior
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:699:in `get_database_version'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/schema_cache.rb:374:in `database_version'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/schema_cache.rb:70:in `database_version'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/schema_cache.rb:200:in `database_version'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract_adapter.rb:871:in `database_version'](http://razvoj:3340/register-finance#)
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:307:in `supports_fetch_first_n_rows_and_offset?'](http://razvoj:3340/register-finance#)
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:271:in `arel_visitor'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract_adapter.rb:159:in `initialize'](http://razvoj:3340/register-finance#)
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:250:in `initialize'](http://razvoj:3340/register-finance#)
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:76:in `new'](http://razvoj:3340/register-finance#)
[oracle-enhanced (deb214decc37) lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:76:in `oracle_enhanced_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:673:in `public_send'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:673:in `new_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:720:in `checkout_new_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:699:in `try_to_checkout_new_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:657:in `acquire_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in `connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_adapters/abstract/connection_handler.rb:246:in `retrieve_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_handling.rb:287:in `retrieve_connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/connection_handling.rb:254:in `connection'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:618:in `load_schema!'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/attributes.rb:264:in `load_schema!'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:563:in `block in load_schema'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:560:in `synchronize'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:560:in `load_schema'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:441:in `attribute_types'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/model_schema.rb:467:in `type_for_attribute'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/type_caster/map.rb:16:in `type_for_attribute'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/arel/table.rb:111:in `type_for_attribute'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/table_metadata.rb:18:in `type'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:59:in `build'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:54:in `[]'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:132:in `block in expand_from_hash'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:79:in `each'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:79:in `flat_map'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/query_methods.rb:1526:in `build_where_clause'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/query_methods.rb:943:in `where!'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/relation/query_methods.rb:938:in `where'](http://razvoj:3340/register-finance#)
[activerecord (7.1.2) lib/active_record/querying.rb:23:in `where'](http://razvoj:3340/register-finance#)
[/home/rails/register/app/renderers/register_renderer.rb:102:in `finance'](http://razvoj:3340/register-finance#)

### System configuration
**Rails version**:  rails (7.1.2)

**Oracle enhanced adapter version**: activerecord-oracle_enhanced-adapter (7.1.0.alpha deb214d)

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

**Oracle Database version**: 12.1.0.2.0

Thanks
TheR

**Comment by jarl-dk** [comment] 2024-03-11 09:25
This request covers https://github.com/rsim/oracle-enhanced/issues/2329

**Comment by andynu** [comment] 2024-03-26 18:28
Hi Everyone,

I'm interested in helping move this forward. I've started a series of PRs to work through test regressions on the way to rails 7.1 support. Right now I'm providing them as stacked PRs so you can see the passing tests. I'd be happy to provide them again as independent PRs, each one really just contains a rails feature bump and a single commit of the fixing changes. Since there is no contribution guide here, I'm not sure if this is the most desirable approach. Please let me know if I can change tactics to make this easier on the maintainers.
 
 I would appreciate any feedback you have. I'm trying to be as minimal as possible in the changes to make these tests pass, there are already scenarios where a larger change might be more appropriate. Thank you!!!
 
 - #2367 
 - #2368
 - #2369
 - #2370
 - #2371
 - #2372
 - #2374
 - #2373
 - #2375
 - #2376
 - #2377

**Comment by davinlagerroos** [comment] 2024-03-27 22:53
First, thanks @andynu for the work you've put in to upgrading this library! 

Second, I am by no means an expert in this library or its patterns. My group uses this gem and I have been looking at a 7.1 update well, so I have some ideas about a couple of these changes that I will add to the relevant PRs. However, I am still orienting myself to the codebase so take whatever I say in those PRs with a grain of salt.

**Comment by joshRpowell** [comment] 2024-05-15 14:11
Anyone know how this recent change in Rails https://github.com/rails/rails/commit/d0af407ec0187555cba332943b7d89262fc532bc impacts this Gem?

**Comment by andynu** [comment] 2024-05-15 14:30
Josh, Some facts:
- Rails's main branch has moved on to rails 8.0.
- Rails's has branched 7-2-stable
- Rails 7.1 released 7 months ago.
- There are no official versions of this gem that supports or tests against
any of those rails versions.

What I take from that commit is just that the rails team itself is limiting
the scope of what they are actively supporting. It does not preclude other
gems continuing to exist and integrate with active-record. But it does put
the entire onus of support on those 3rd party gems. Said another way: We're
on our own.

**Comment by mohits** [comment] 2024-05-15 15:38
I remember the discussion that support will be provided officially by Rails core for the major supported OSS databases. The discussion was in the context of DB2 support and is at this link: https://github.com/rails/rails/issues/50537

In fact, this gem was specifically mentioned in the discussion. I read it as meaning that Rails core will officially support only those adapters but the community is welcome to add support for others and yes, the onus is on them and their users. However, I have no doubt that changes could be upstreamed to Rails if it were broadly applicable.

**Comment by jacobat** [comment] 2024-05-27 07:38
@yahonda Are you aware of anyone working on providing a Rails 7.1 compatible version beyond what's mentioned in this thread? Are you still working on this adapter or do we need to find new maintainer(s)?

**Comment by yahonda** [comment] 2024-05-27 12:11
Sorry for my late update. I still have some plan to support Oracle enhanced adapter compatible with Rails 7.1. That will take some more time.

**Comment by hss-mateus** [comment] 2024-07-05 19:21
#2384 have all the patches mentioned above and a couple of more things

Unfortunatelly I don't have time to test it with different scenarios than a simple model

**Comment by rjschof** [comment] 2024-08-09 15:33
This is a blocker for any app relying on Oracle DBs to get to Rails 7.1. It looks like the code in the PR #2384 works pretty well. What needs to be done to get this in a new release of this gem? How can I help?

**Comment by dwarner** [comment] 2024-09-09 11:39
I see the code has been merged into master (i.e. 7.1.0.alpha), but Is there an estimate on the official release date of 7.1.0?

**Comment by joshRpowell** [comment] 2024-09-22 19:36
@dwarner a tagged beta is now available for testing https://github.com/rsim/oracle-enhanced/releases/tag/v7.1.0.beta1

**Comment by andynu** [comment] 2024-09-23 15:14
I've switched to this from my fork. So far, so good. Tests are green. Nothing surprising yet. Thank you so much @yahonda for cutting the public release.

**Comment by Faq** [comment] 2024-09-26 11:07
With release of v7.1, forgotten to update readme too or that only for major versions? https://github.com/rsim/oracle-enhanced#installation

**Comment by yahonda** [comment] 2024-09-26 22:59
Thank you for waiting for the release of Active Record Oracle enhanced adapter 7.1. The README has been updated via #2408 as well, so I am going to close this issue. If you encounter any problems, please feel free to open a new issue.

**Closed by yahonda** 2024-09-26 22:59 UTC
