### ISSUE TITLE
Rails 5 migration/schema dump issue/question with postgres and OracleEnhancedAdaptor

### ISSUE THREAD

**Issue by landesjm** [rsim/oracle-enhanced#797] opened 2016-04-01 14:15 UTC
I'm using Rails5.0.0.beta3 with multiple database connections, one to postgres and one to Oracle (legacy tables). When I execute rake db:migrate or rake db:schema:dump, an error is generated which appears that the OEA is asking the Postgres adaptor for a listing of it's materialized views. I posted this to Rails which indicated this is an OEA issue.

```ruby
$ rake db:schema:dump
rake aborted!
NoMethodError: undefined method materialized_views' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007ff33b5a9110> Dev/projects/Storeburst/vendor/ruby/2.3.0/bundler/gems/oracle-enhanced-3f31fcc86f06/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:30:intables'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema_dumper.rb:37:in dump' Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/schema_dumper.rb:21:indump'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:253:in block (4 levels) in <top (required)>' Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:252:inopen'
Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:252:in block (3 levels) in <top (required)>' .rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:ineval'
.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `

'
Tasks: TOP => db:schema:dump
```

If I comment out the OEA gem in the Gemfile, the db:migrate and db:schema:dump work as expected. 

The OEA gem is from the rails5 branch - 
gem 'activerecord-oracle_enhanced-adapter', :git => 'https://github.com/rsim/oracle-enhanced.git', :branch => 'rails5'

**Comment by yahonda** [comment] 2016-04-05 11:54
Thanks for reporting. Schema dumper need to have the same name space as bundled database adapters, postgresql, mysql2 and sqlite3. 

Oracle enhanced adapter Rails 5 support is still under development. I'll keep this open but as of right now suggested workaround is commented out activerecord-oracle_enhanced-adapter from your Gemfile and uninstall it.

**Comment by landesjm** [comment] 2016-07-22 16:05
checking on the work to have the Schema dumper work within a name space?

**Comment by yahonda** [comment] 2016-07-22 17:05
Thanks for the update. There are couple of changes made in `SchemaDumper` since this issue reported. But unfortulately unit testing does not cover use cases co-existing PostgreSQL and Oracle databases.

It would be appreciated that updating the Gemfile to use 1.7.0.beta2 and update the result.
```ruby
gem 'activerecord-oracle_enhanced-adapter', '~> 1.7.0.beta2'
```

**Comment by yahonda** [comment] 2016-07-22 18:18
If `1.7.0.beta2` does not address this error, would you give it a try this entry and update the result.

```ruby
  gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'diag797'
```

**Comment by landesjm** [comment] 2016-07-26 13:16
I updated to 1.7.0.beta2 with the same result of sending the 'materialized_views' method to the PostgreSQL connection. Subsequent update to 'yahonda/oracle-enhanced' branch yielded this stack trace. 

rake aborted!
NoMethodError: undefined method `materialized_views' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f9fb8cd96a0>
/Dev/projects/Storeburst/vendor/ruby/2.3.0/bundler/gems/oracle-enhanced-bd8ec7544da7/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:10:in `tables'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:37:in `dump'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:21:in `dump'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:252:in `open'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/Dev/projects/Storeburst/vendor/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)

**Comment by landesjm** [comment] 2016-07-26 13:25
Same issue using the 1.7.0.beta3 release. Let me know if there is anything else I can help with

**Comment by yahonda** [comment] 2016-07-27 02:29
Thanks for the update.  I think I need to create a environment running PostgreSQL and Oracle database. It will be helpful to get these information to reproduce.

* How does each environment connect to each database, `database.yml` information including `adapter` information is appreciated
* PostgreSQL database version
* Oracle database version
* Ruby version
* `bundle show` output
* This configuration has been working using Rails 4.2 or lower version of Rails or not

**Comment by landesjm** [comment] 2016-07-27 20:22
I have a different application that connects to both PostgreSQL and Oracle using Rails 4.2.6 and Ruby 2.2.0. This app I started on Rails 5 and Ruby 2.3.0. Both apps connect to the same PostgreSQL and Oracle databases. 

Oracle version: 11.2 
PostgreSQL version: 9.2.15 
Ruby version: 2.3.0

database.yml (sample)
default: &default
  adapter: postgresql
  username: <USERNAME>
  password: <PASSWORD>

development:
  <<: *default
  database: <DATABASE NAME>

test:
  <<: *default
  database: <DATABASE NAME TEST>

pos_default: &pos_default
  adapter: oracle_enhanced
  database: <ORACLE SERVICE NAME>
  host: <DATABASE SERVER NAME>
  port: 1521
  pool: 5
  timeout: 5000

pos_storeord:
  <<: *pos_default
  username: <USERNAME>
  password: <PASSWORD>
  target_schema_name: <SCHEMA_NAME>

pos_storeord_test:
  <<: *pos_default
  username: <USERNAME_TEST>
  password: <PASSWORD>
  target_schema_name: <SCHEMA_NAME_TEST>

$ bundle show 
Gems included by the bundle:
  * actioncable (5.0.0)
  * actionmailer (5.0.0)
  * actionpack (5.0.0)
  * actionview (5.0.0)
  * activejob (5.0.0)
  * activemodel (5.0.0)
  * activerecord (5.0.0)
  * activerecord-oracle_enhanced-adapter (1.7.0.beta3)
  * activesupport (5.0.0)
  * addressable (2.4.0)
  * airbrussh (1.0.2)
  * ansi (1.5.0)
  * arel (7.1.0)
  * autoprefixer-rails (6.3.7)
  * bcrypt (3.1.11)
  * bootstrap-sass (3.3.7)
  * builder (3.2.2)
  * bundler (1.12.5)
  * byebug (9.0.5)
  * capistrano (3.5.0)
  * capistrano-bundler (1.1.4)
  * capistrano-harrow (0.5.2)
  * capistrano-passenger (0.2.0)
  * capistrano-rails (1.1.7)
  * capistrano-rvm (0.1.2)
  * capybara (2.7.1)
  * childprocess (0.5.9)
  * chronic (0.10.2)
  * coffee-rails (4.2.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.2)
  * debug_inspector (0.0.2)
  * devise (4.2.0 13d4fd4)
  * devise_ldap_authenticatable (0.8.5)
  * diff-lcs (1.2.5)
  * domain_name (0.5.20160615)
  * erubis (2.7.0)
  * execjs (2.7.0)
  * ffi (1.9.14)
  * globalid (0.3.6)
  * haml (4.0.7)
  * honeybadger (2.6.0)
  * http (2.0.2)
  * http-cookie (1.0.2)
  * http-form_data (1.0.1)
  * http_parser.rb (0.6.0)
  * i18n (0.7.0)
  * jquery-rails (4.1.1)
  * launchy (2.4.3)
  * letter_opener (1.4.1)
  * libv8 (3.16.14.15)
  * loofah (2.0.3)
  * mail (2.6.4)
  * metaclass (0.0.4)
  * method_source (0.8.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mini_portile2 (2.1.0)
  * minitest (5.9.0)
  * minitest-reporters (1.1.10)
  * mocha (1.1.0)
  * net-ldap (0.11)
  * net-scp (1.2.1)
  * net-ssh (3.2.0)
  * nio4r (1.2.1)
  * nokogiri (1.6.8)
  * orm_adapter (0.5.0)
  * pg (0.18.4)
  * pkg-config (1.1.7)
  * puma (3.6.0)
  * rack (2.0.1)
  * rack-test (0.6.3)
  * rails (5.0.0)
  * rails-dom-testing (2.0.1)
  * rails-html-sanitizer (1.0.3)
  * railties (5.0.0)
  * rake (11.2.2)
  * ref (2.0.0)
  * responders (2.2.0)
  * rspec (3.5.0)
  * rspec-core (3.5.1)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * ruby-oci8 (2.2.2)
  * ruby-plsql (0.6.0)
  * ruby-progressbar (1.8.1)
  * rubyzip (1.2.0)
  * sass (3.4.22)
  * sass-rails (5.0.6)
  * selenium-webdriver (2.53.4)
  * spring (1.7.2)
  * sprockets (3.7.0)
  * sprockets-rails (3.1.1)
  * sshkit (1.11.1)
  * therubyracer (0.12.2)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * turbolinks (5.0.0)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.2)
  * uglifier (3.0.0)
  * unf (0.1.4)
  * unf_ext (0.0.7.2)
  * warden (1.2.6)
  * web-console (3.3.1)
  * websocket (1.2.3)
  * websocket-driver (0.6.4)
  * websocket-extensions (0.1.2)
  * whenever (0.9.7)
  * xpath (2.0.0)

**Comment by yahonda** [comment] 2016-07-27 20:25
Thanks for the update. Appreciated.

**Comment by jeffrey-s-foster** [comment] 2016-07-29 21:39
Here's a sequence of actions that triggers the bug, starting from scratch:

1. `rails generate tmp`
2. Add the following to Gemfile:
gem 'activerecord-oracle_enhanced-adapter', '~> 1.7.0.beta6'
3. `bundle install`
4. `rails generate migration user name:string`
5. `rake db:migrate`

Yields:

NoMethodError: undefined method `materialized_views' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:...>

No actual Oracle db needed...

Ruby version 2.3.1p112

Gems included by the bundle:
  * actioncable (5.0.0)
  * actionmailer (5.0.0)
  * actionpack (5.0.0)
  * actionview (5.0.0)
  * activejob (5.0.0)
  * activemodel (5.0.0)
  * activerecord (5.0.0)
  * activerecord-oracle_enhanced-adapter (1.7.0.beta6)
  * activesupport (5.0.0)
  * arel (7.1.1)
  * builder (3.2.2)
  * bundler (1.12.3)
  * byebug (9.0.5)
  * coffee-rails (4.2.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.2)
  * debug_inspector (0.0.2)
  * erubis (2.7.0)
  * execjs (2.7.0)
  * ffi (1.9.14)
  * globalid (0.3.7)
  * i18n (0.7.0)
  * jbuilder (2.6.0)
  * jquery-rails (4.1.1)
  * listen (3.0.8)
  * loofah (2.0.3)
  * mail (2.6.4)
  * method_source (0.8.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mini_portile2 (2.1.0)
  * minitest (5.9.0)
  * multi_json (1.12.1)
  * nio4r (1.2.1)
  * nokogiri (1.6.8)
  * pkg-config (1.1.7)
  * puma (3.6.0)
  * rack (2.0.1)
  * rack-test (0.6.3)
  * rails (5.0.0)
  * rails-dom-testing (2.0.1)
  * rails-html-sanitizer (1.0.3)
  * railties (5.0.0)
  * rake (11.2.2)
  * rb-fsevent (0.9.7)
  * rb-inotify (0.9.7)
  * ruby-oci8 (2.2.2)
  * ruby-plsql (0.6.0)
  * sass (3.4.22)
  * sass-rails (5.0.6)
  * spring (1.7.2)
  * spring-watcher-listen (2.0.0)
  * sprockets (3.7.0)
  * sprockets-rails (3.1.1)
  * sqlite3 (1.3.11)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * turbolinks (5.0.0)
  * turbolinks-source (5.0.0)
  * tzinfo (1.2.2)
  * uglifier (3.0.1)
  * web-console (3.3.1)
  * websocket-driver (0.6.4)
  * websocket-extensions (0.1.2)

**Comment by yahonda** [comment] 2016-08-01 12:44
Thanks for providing steps to reproduce.  I have created a tentative fix for this issue.

```ruby
  gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'diag797'
```
@landesjm  @jeffrey-s-foster 
Would you update your Gemfile and see if it still reproduces or not.

**Comment by jeffrey-s-foster** [comment] 2016-08-01 14:16
Just made a migration for my app and did `rake db:migrate`, and it worked fine with this version, thanks!

**Comment by jeffrey-s-foster** [comment] 2016-08-01 14:19
Sorry, I spoke too soon. There were no errors reported on the command-line, but schema.rb was trashed by the update. The create_table lines were replaced by this error:

#   undefined method `temporary_table?' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fb6ba6d0dd0>

**Comment by yahonda** [comment] 2016-08-01 14:31
Thanks for testing. Would you provide full stack trace for this `undefined method `temporary_table?'`

**Comment by jeffrey-s-foster** [comment] 2016-08-01 15:05
I had to hack schema_dumper.rb to print it out, but here you go:

```
#   undefined method `temporary_table?' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007fd9a26ed218>
.../.rvm/gems/ruby-2.3.1/bundler/gems/oracle-enhanced-e438aee70052/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:104:in `table'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:91:in `block in tables'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:90:in `each'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:90:in `tables'
.../.rvm/gems/ruby-2.3.1/bundler/gems/oracle-enhanced-e438aee70052/lib/active_record/connection_adapters/oracle_enhanced/schema_dumper.rb:9:in `tables'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:37:in `dump'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/schema_dumper.rb:21:in `dump'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:252:in `open'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
.../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
.../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
.../.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:145:in `block (2 levels) in <top (required)>'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
.../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
.../.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
.../.rvm/gems/ruby-2.3.1/bin/rake:23:in `load'
.../.rvm/gems/ruby-2.3.1/bin/rake:23:in `<main>'
.../.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
.../.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yahonda** [comment] 2016-08-01 15:33
Thanks for providing the full stack trace. I have added another commit to the branch:

```ruby
  gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'diag797'
```

Execute `bundle update` to get the latest commit https://github.com/yahonda/oracle-enhanced/commit/817ef9c80d8974777f62b6e24dda6db8e979a893 and check your `schema.rb`
```ruby
$ bundle update
```
Thanks.

**Comment by jeffrey-s-foster** [comment] 2016-08-01 15:39
That fixed the problem, thanks!

**Comment by yahonda** [comment] 2016-08-01 15:42
Thanks for testing. #947 has been merged to master, and releasing new beta version.
Thanks again for testing and reports.

**Closed by yahonda** 2016-08-01 15:42 UTC

**Comment by landesjm** [comment] 2016-08-01 20:23
thanks for fixing.
