### ISSUE TITLE
Time column behaviour is different from other versions (1.6)

### ISSUE THREAD

**Issue by jameschenjav** [rsim/oracle-enhanced#1611] opened 2017-12-22 02:59 UTC
### Steps to reproduce
1. Model `Foo` contains a timestamp column `bar`.
2. Get an instance: `foo = Foo.first`
3. Assign a string to the timestamp column `foo.bar = '2017-12-22 01:02:03'`

### Expected behavior
The type of `foo.bar` should be `Time` or similar types like `ActiveSupport::TimeWithZone`

### Actual behavior
It's `String` in 1.6
I tested it in 1.5~1.8. All the other versions are correct.

### System configuration
**Rails version**:
4.2.10

**Oracle enhanced adapter version**:
1.6.9 (from Gemfile.lock)

**Ruby version**:
2.4.2

**Oracle Database version**:
11g release 11.2.0.1.0

**Comment by yahonda** [comment] 2017-12-26 19:59
Hi, Would you create a executable test case based on `active_record_gem.rb` or `active_record_gem_spec.rb`  at https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates

Thank you.

**Comment by eGust** [comment] 2017-12-29 01:10
would these be ok?

[bug_report_templates.zip](https://github.com/rsim/oracle-enhanced/files/1592407/bug_report_templates.zip)

fail only
```ruby
  gem "rails", github: "rails/rails", branch: "4-2-stable"
  gem "arel" #, github: "rails/arel", branch: "master"
  gem "activerecord-oracle_enhanced-adapter",  github: "rsim/oracle-enhanced", branch: "release16"
```

```
  1) bug test should be a Time type after assigning
     Failure/Error: expect(post.created_at.class.name).to eq("Time") # both Time and ActiveSupport::TimeWithZone use "Time"

       expected: "Time"
            got: "String"

       (compared using ==)
     # ./active_record_gem_spec.rb:65:in `block (2 levels) in <top (required)>'
```

### active_record_gem.rb
```ruby
ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamp :created_at
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_timestamp_assignment
    post = Post.new
    post.created_at = "2000-01-02 03:04:05"
    assert_equal post.created_at.class.name, "Time" # both Time and ActiveSupport::TimeWithZone
  end
end
```

### active_record_gem_spec.rb
```ruby
describe "bug test" do
  before(:all) do
    ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
    ActiveRecord::Schema.define do
      create_table :posts, force: true do |t|
        t.timestamp :created_at
      end
    end
    class Post < ActiveRecord::Base
      has_many :comments
    end
  end

  it "should be a Time type after assigning" do
    post = Post.new
    post.created_at = "2000-01-02 03:04:05"
    expect(post.created_at.class.name).to eq("Time") # both Time and ActiveSupport::TimeWithZone
  end
end
```

**Comment by yahonda** [comment] 2018-01-04 15:45
Thanks for providing a test case to reproduce it with Rails `4-2-stable` and Oracle enhanced adapter `release16` branch. As long as it reproduces you can choose RSpec or minitest you prefer. no need to provide both.

As you mentioned it does not reproduce with Rails `5-0-stable` branch or higher and Rails 4.2 is not supported anymore, what I can suggest are:

* Upgrading to higher version such as Rails 5.1
* Cherry pick #1620 yourself

Unfortunately, as Rails 4.2.x is not supported anymore and I do not maintain older version of Oracle enhanced adapter for non supported version of Rails no fix will be available for `release16` branch.

Thanks again for providing a test case, which helped me a lot.

**Comment by bardbess** [comment] 2018-01-04 20:35
Ok Thank you @yahonda I will use #1620 for `release16` to get our application stable first.

I am working on moving a project forward to a supported Rails version, currently implementing Rails attribute API for `4-2-stable` since `release17` no longer works with `is_xxx_columns?` and the application is very large with a very old database.

The following is an extract from `release17`
```
def self.is_date_column?(name, table_name = nil)
    ActiveSupport::Deprecation.warn(<<-MSG.squish)
      `self.is_date_column?` has been deprecated. Please use Rails attribute API.
    MSG
    return false
    # name =~ /(^|_)date(_|$)/i
  end
```

Thank you for your time and consideration.

**Comment by yahonda** [comment] 2018-01-08 17:29
Closing since workaround provided for the original issue. 

If there is a issue for `def self.is_date_column` method deprecation and removal, would you open another one with steps to reproduce.

Thank you.

**Closed by yahonda** 2018-01-08 17:29 UTC
