### ISSUE TITLE
Error running schema:load when schema.rb has add_foreign_key

### ISSUE THREAD

**Issue by chao-xian** [rsim/oracle-enhanced#604] opened 2015-05-27 14:22 UTC
Hi

We keep hitting the error below (full stack is further down) when we run `rake db:schema:load` on a clean database:
```
-- create_table("profiles", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-02449: unique/primary keys in table referenced by foreign keys: DROP TABLE "PROFILES"
stmt.c:230:in oci8lib_200.so
```

In the `schema.rb` the foreign key is defined:
`add_foreign_key "urls", "profiles", name: "urls_profile_id_fk"`

Removing this from the `schema.rb` file gets rid of the error, but why is it trying to drop the table before adding the foreign key constraint?

I tried it out with a MySQL adapter and ran `rake db:schema:load` with the same `schema.rb` file and that worked fine. Have also tried updating to latest gems for this project (we are using the `rails42` branch) and `ruby-oci8` gem just to be sure but still get the error.

Stack trace:
```
-- create_table("profiles", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-02449: unique/primary keys in table referenced by foreign keys: DROP TABLE "PROFILES"
stmt.c:230:in oci8lib_200.so
/home/vagrant/.gem/ruby/gems/ruby-oci8-2.1.7/lib/oci8/cursor.rb:129:in `exec'
/home/vagrant/.gem/ruby/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:278:in `exec_internal'
/home/vagrant/.gem/ruby/gems/ruby-oci8-2.1.7/lib/oci8/oci8.rb:269:in `exec'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:431:in `exec'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_oci_connection.rb:90:in `exec'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `block in execute'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/vagrant/.gem/ruby/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/vagrant/.gem/ruby/gems/rack-mini-profiler-0.9.3/lib/patches/db/activerecord.rb:17:in `log_with_miniprofiler'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1300:in `log'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_database_statements.rb:10:in `execute'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:373:in `drop_table'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb:117:in `drop_table'
/home/vagrant/.gem/ruby/bundler/gems/oracle-enhanced-2e739cf446a6/lib/active_record/connection_adapters/oracle_enhanced_schema_statements.rb:79:in `create_table'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/opt/www/apps/cms-editor/db/schema.rb:92:in `block in <top (required)>'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `instance_eval'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/schema.rb:41:in `define'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/schema.rb:61:in `define'
/opt/www/apps/cms-editor/db/schema.rb:14:in `<top (required)>'
/home/vagrant/.gem/ruby/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/.gem/ruby/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/vagrant/.gem/ruby/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.gem/ruby/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'
/home/vagrant/.gem/ruby/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:244:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:schema:load
```

**Comment by yahonda** [comment] 2015-06-20 00:12
#593 may (or may not) help this issue. Please try the latest 1.6.0.beta to support Rails 4.2.

```ruby
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0.beta1" 
```

**Comment by yahonda** [comment] 2015-10-12 20:59
Closing it since no feedback available.  Please reopen if it still reproduce using the latest version of Oracle enhanced adapter.

```ruby
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0"
```

**Closed by yahonda** 2015-10-12 20:59 UTC

**Comment by chao-xian** [comment] 2015-12-01 22:30
Hi

Sorry for not responding earlier. We upgraded to 1.6.1 a while back but we hadn't been running that task. Ran `db:setup` just today and that seems to be fine now. 

Thank you also for your hard work on this gem :+1:

**Comment by yahonda** [comment] 2015-12-01 22:38
good to know. Thanks.
