### ISSUE TITLE
No DLL is found to hook.

### ISSUE THREAD

**Issue by harveyflinn** [rsim/oracle-enhanced#2262] opened 2022-02-18 22:25 UTC
### Steps to reproduce
Please refer https://github.com/rsim/oracle-enhanced/tree/master/guides/bug_report_templates
to create an executable test case

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Oracle enhanced adapter version**:

**Ruby version**:

**Oracle Database version**:

**Comment by harveyflinn** [comment] 2022-02-18 22:29
I am on Windows 10 with 
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
Rails 7.0.2.2

I execute db:schema:dump and get:
>rails db:schema:dump --trace
** Invoke db:schema:dump (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:schema:dump
rails aborted!
No DLL is found to hook.
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ruby-oci8-2.2.10-x64-mingw32/lib/oci8/properties.rb:74:in `__set_prop'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ruby-oci8-2.2.10-x64-mingw32/lib/oci8/properties.rb:74:in `[]='

I do not know what DLL is not found or if it is hook.dll.  Any suggestions appreciated.
Harvey

**Comment by kubo** [comment] 2022-02-19 09:07
@harveyflinn 
This is an issue of ruby-oci8. I reproduced it with Oracle XE 21c. I'll fix it.

**Comment by harveyflinn** [comment] 2022-02-22 15:46
Thanks Kubo.  I now get a different "No DLL is found to hook"
[RubyRailsUpdate.txt](https://github.com/rsim/oracle-enhanced/files/8117951/RubyRailsUpdate.txt)
 I have attached a file showing the error.

I did a "gem update" followed by "bundle install" followed by "rails db:shema:dump" .

In summary, I got ...
C:\Users\HFLINN2\Desktop\RailsProjects\AfterInstall>rails db:schema:dump
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:22: warning: previous definition of SAME_PATHS was here
C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:31: warning: already initialized constant Pathname::SEPARATOR_LIST
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:31: warning: previous definition of SEPARATOR_LIST was here
C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:32: warning: already initialized constant Pathname::SEPARATOR_PAT
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:32: warning: previous definition of SEPARATOR_PAT was here
C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:39: warning: already initialized constant Pathname::ABSOLUTE_PATH
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:39: warning: previous definition of ABSOLUTE_PATH was here
C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::TYPE_VOID
C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::TYPE_VOIDP
.
.
.
C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::Handle::RTLD_NOW
C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::NULL
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle/version.rb:2: warning: already initialized constant Fiddle::VERSION
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle/version.rb:2: warning: previous definition of VERSION was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBALC:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:67: warning: previous definition of RTLD_GLOBAL was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:68: warning: previous definition of RTLD_LAZY was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:69: warning: previous definition of RTLD_NOW was here
rails aborted!
No DLL is found to hook.

Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)

C:\Users\HFLINN2\Desktop\RailsProjects\AfterInstall>

C:\Users\HFLINN2\Desktop\RailsProjects\AfterInstall>ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

C:\Users\HFLINN2\Desktop\RailsProjects\AfterInstall>rails --version
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Rails 7.0.2.2

**Comment by harveyflinn** [comment] 2022-02-22 17:14
Thanks Kubo.
I am now getting the following error when I execute:
rails db:schema:dump --trace

C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::Handle::RTLD_NOW
C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so: warning: already initialized constant Fiddle::NULL
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle/version.rb:2: warning: already initialized constant Fiddle::VERSION
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle/version.rb:2: warning: previous definition of VERSION was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBAL
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:67: warning: previous definition of RTLD_GLOBAL was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:68: warning: previous definition of RTLD_LAZY was here
C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/fiddle-1.1.0/lib/fiddle.rb:69: warning: previous definition of RTLD_NOW was here
** Invoke db:schema:dump (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:schema:dump
rails aborted!
OCIError: ORA-12154: TNS:could not resolve the connect identifier specified
oci8.c:557:in oci8lib_300.so
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ruby-oci8-2.2.11-x64-mingw32/lib/oci8/oci8.rb:142:in `initialize'**
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:341:in `new'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:341:in `new_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:393:in `initialize'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `new'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:31:in `initialize'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `new'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced/connection.rb:11:in `create'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-oracle_enhanced-adapter-7.0.2/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:77:in `oracle_enhanced_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `new_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:700:in `checkout_new_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:679:in `try_to_checkout_new_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:640:in `acquire_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:341:in `checkout'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:211:in `retrieve_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_handling.rb:313:in `retrieve_connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/connection_handling.rb:280:in `connection'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/tasks/database_tasks.rb:423:in `dump_schema'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/railties/databases.rake:460:in `block (4 levels) in <main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/railties/databases.rake:457:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-7.0.2.2/lib/active_record/railties/databases.rake:457:in `block (3 levels) in <main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:51:in `invoke'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:dump

**Comment by yahonda** [comment] 2022-02-25 02:29
These warnings are not related to ruby-oci8. How about updating bunler and thor to see if these warnings disappears?

bundle update --bundler
bundle update thor

If not please refer to these issues


> Calling DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call DidYouMean.correct_error(error_name, spell_checker)' instead.

This warning should have been fixed by thor v1.20.0 or higher. https://github.com/rails/thor/pull/761

> C:/Ruby30-x64/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH

These warnings looks like fixed by Bundler 2.2.33 or higher https://github.com/ruby/pathname/issues/12

**Closed** 2022-06-07 12:23 UTC
