### ISSUE TITLE
Failed to save BigDecimal values

### ISSUE THREAD

**Issue by AgeevAndrew** [rsim/oracle-enhanced#1136] opened 2017-01-11 06:37 UTC
Hi,

After upgrade to Rails5 and new version of this gem (from 1.6.7 to 1.7.9), I got an error with save object, contains decimal columns - ActiveRecord::StatementInvalid: OCIError: ORA-01722: Invalid Number

```ruby
Backtrace:
`ActiveRecord::StatementInvalid: OCIError: ORA-01722: Invalid Number: UPDATE "PLAN_SPEC_AMOUNTS" SET "AMOUNT_FINANCE" = :a1 WHERE "PLAN_SPEC_AMOUNTS"."ID" = :a2
	from stmt.c:243:in oci8lib_230.so
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:129:in `exec'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:178:in `exec_update'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:151:in `block in exec_update'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1284:in `log'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:135:in `exec_update'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `update'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/relation.rb:89:in `_update_record'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/persistence.rb:545:in `_update_record'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/locking/optimistic.rb:79:in `_update_record'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/dirty.rb:119:in `_update_record'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/callbacks.rb:306:in `block in _update_record'
... 21 levels...
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:319:in `block in save'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:318:in `save'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0/lib/active_record/suppressor.rb:41:in `save'
	from (irb):5
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/andrew/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Here is that column:
```ruby
#<ActiveRecord::ConnectionAdapters::OracleEnhancedColumn:0x0055ee45a1d8d8 @virtual=false, @returning_id=false, @name="amount_finance", @table_name="plan_spec_amounts", @sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x0055ee45a1d9a0 @sql_type="NUMBER(18,2)", @type=:decimal, @limit=nil, @precision=18, @scale=2>, @null=true, @default=nil, @default_function=nil, @collation=nil, @comment="Финансирование без НДС", @object_type=false>
```

What should I do with decimal values?
There is nothing about this in "upgrade" section of ReadMe https://github.com/rsim/oracle-enhanced#upgrade

**Comment by yahonda** [comment] 2017-01-11 14:16
Thanks for upgrading Rails and Oracle enhanced adapter.

Would you create a test case to reproduce this error? https://github.com/rsim/oracle-enhanced/blob/release17/guides/bug_report_templates/active_record_gem.rb

Thanks.

**Comment by AgeevAndrew** [comment] 2017-01-11 23:11
This is it.

`
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '~> 5.0.0'
  gem 'activerecord-oracle_enhanced-adapter', '~> 1.7.0'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.decimal :price, precision: 18, scale: 2
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_save_record_with_bigdecimal
    post = Post.create!(price: 2134.02)

    # assert_equal 1, post.comments.count
    # assert_equal 1, Comment.count
    # assert_equal post.id, Comment.first.post.id
  end
end
`

**Comment by yahonda** [comment] 2017-01-17 19:12
Thanks for the update. Executed the script and finishes without errors. Would you confirm this script represents your original issues.


```ruby
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ ruby rep1136.rb
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using concurrent-ruby 1.0.4
Using i18n 0.7.0
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using ruby-plsql 0.6.0
Using bundler 1.13.7
Using method_source 0.8.2
Using thor 0.19.4
Using ruby-oci8 2.2.3
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.4
Using mime-types 3.1
Using activesupport 5.0.1
Using loofah 2.0.3
Using mail 2.6.4
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.0.1
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.1
Using activerecord 5.0.1
Using actionview 5.0.1
Using activerecord-oracle_enhanced-adapter 1.7.9
Using actionpack 5.0.1
Using actioncable 5.0.1
Using actionmailer 5.0.1
Using railties 5.0.1
Using sprockets-rails 3.2.0
Using rails 5.0.1
/home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/yahonda/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
-- create_table(:posts, {:force=>true})
D, [2017-01-17T19:10:38.100569 #8547] DEBUG -- :    (35.6ms)  DROP TABLE "POSTS"
D, [2017-01-17T19:10:38.111165 #8547] DEBUG -- :    (9.9ms)  DROP SEQUENCE "POSTS_SEQ"
D, [2017-01-17T19:10:38.130876 #8547] DEBUG -- :    (19.1ms)  CREATE TABLE "POSTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "PRICE" DECIMAL(18,2))
D, [2017-01-17T19:10:38.135816 #8547] DEBUG -- :    (4.5ms)  CREATE SEQUENCE "POSTS_SEQ" START WITH 10000
   -> 0.1132s
D, [2017-01-17T19:10:38.307119 #8547] DEBUG -- :    (30.6ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'ORACLE_ENHANCED' AND cols.table_name = 'AR_INTERNAL_METADATA' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-01-17T19:10:38.315483 #8547] DEBUG -- :   ActiveRecord::InternalMetadata Load (3.2ms)  SELECT  "AR_INTERNAL_METADATA".* FROM "AR_INTERNAL_METADATA" WHERE "AR_INTERNAL_METADATA"."KEY" = :a1 FETCH FIRST :a2 ROWS ONLY  [["key", :environment], ["LIMIT", 1]]
Run options: --seed 47471

# Running:

D, [2017-01-17T19:10:38.378294 #8547] DEBUG -- :    (35.1ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'ORACLE_ENHANCED' AND cols.table_name = 'POSTS' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-01-17T19:10:38.509492 #8547] DEBUG -- :   Sequence (1.5ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ORACLE_ENHANCED' and us.sequence_name = 'POSTS_SEQ'
D, [2017-01-17T19:10:38.517764 #8547] DEBUG -- :   Primary Key (7.8ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ORACLE_ENHANCED' AND c.table_name = 'POSTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2017-01-17T19:10:38.529996 #8547] DEBUG -- :   Sequence (2.9ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ORACLE_ENHANCED' and us.sequence_name = 'POSTS_SEQ'
D, [2017-01-17T19:10:38.532846 #8547] DEBUG -- :   Primary Key (2.5ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ORACLE_ENHANCED' AND c.table_name = 'POSTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2017-01-17T19:10:38.534875 #8547] DEBUG -- :   Primary Key Trigger (1.7ms)            SELECT trigger_name
          FROM all_triggers
          WHERE owner = 'ORACLE_ENHANCED'
            AND trigger_name = 'POSTS_PKT'
            AND table_owner = 'ORACLE_ENHANCED'
            AND table_name = 'POSTS'
            AND status = 'ENABLED'

D, [2017-01-17T19:10:38.568695 #8547] DEBUG -- :   SQL (25.0ms)  INSERT INTO "POSTS" ("PRICE", "ID") VALUES (:a1, :a2)  [["price", 0.213402e4], ["id", 10000]]
.

Finished in 0.235866s, 4.2397 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
$
```

Thanks.

**Comment by AgeevAndrew** [comment] 2017-01-18 03:44
I have got an error

```
➜  projects ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
➜  projects ruby bug_bigdecimal_save.rb
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using concurrent-ruby 1.0.4
Using i18n 0.7.0
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.4
Using ruby-plsql 0.6.0
Using bundler 1.13.7
Using method_source 0.8.2
Using thor 0.19.4
Using ruby-oci8 2.2.3
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using sprockets 3.7.1
Using websocket-driver 0.6.4
Using mime-types 3.1
Using activesupport 5.0.1
Using loofah 2.0.3
Using mail 2.6.4
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.0.1
Using rails-html-sanitizer 1.0.3
Using activejob 5.0.1
Using activerecord 5.0.1
Using actionview 5.0.1
Using activerecord-oracle_enhanced-adapter 1.7.9
Using actionpack 5.0.1
Using actioncable 5.0.1
Using actionmailer 5.0.1
Using railties 5.0.1
Using sprockets-rails 3.2.0
Using rails 5.0.1
/home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
-- create_table(:posts, {:force=>true})
D, [2017-01-18T13:37:33.533476 #17739] DEBUG -- :    (73.9ms)  DROP TABLE "POSTS"
D, [2017-01-18T13:37:33.551907 #17739] DEBUG -- :    (17.6ms)  DROP SEQUENCE "POSTS_SEQ"
D, [2017-01-18T13:37:33.587404 #17739] DEBUG -- :    (34.4ms)  CREATE TABLE "POSTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "PRICE" DECIMAL(18,2))
D, [2017-01-18T13:37:33.599612 #17739] DEBUG -- :    (11.5ms)  CREATE SEQUENCE "POSTS_SEQ" START WITH 10000
   -> 0.4316s
D, [2017-01-18T13:37:37.245630 #17739] DEBUG -- :    (13.5ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'ANDREW' AND cols.table_name = 'AR_INTERNAL_METADATA' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-01-18T13:37:37.253348 #17739] DEBUG -- :   ActiveRecord::InternalMetadata Load (3.8ms)  SELECT  "AR_INTERNAL_METADATA".* FROM "AR_INTERNAL_METADATA" WHERE "AR_INTERNAL_METADATA"."KEY" = :a1 FETCH FIRST :a2 ROWS ONLY  [["key", :environment], ["LIMIT", 1]]
Run options: --seed 21993

# Running:

D, [2017-01-18T13:37:37.294386 #17739] DEBUG -- :    (11.2ms)  SELECT cols.column_name AS name, cols.data_type AS sql_type, cols.data_default, cols.nullable, cols.virtual_column, cols.hidden_column, cols.data_type_owner AS sql_type_owner, DECODE(cols.data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale, comments.comments as column_comment FROM all_tab_cols cols, all_col_comments comments WHERE cols.owner = 'ANDREW' AND cols.table_name = 'POSTS' AND cols.hidden_column = 'NO' AND cols.owner = comments.owner AND cols.table_name = comments.table_name AND cols.column_name = comments.column_name ORDER BY cols.column_id
D, [2017-01-18T13:37:37.442572 #17739] DEBUG -- :   Sequence (2.5ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ANDREW' and us.sequence_name = 'POSTS_SEQ'
D, [2017-01-18T13:37:37.474028 #17739] DEBUG -- :   Primary Key (31.1ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ANDREW' AND c.table_name = 'POSTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2017-01-18T13:37:37.487066 #17739] DEBUG -- :   Sequence (4.9ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ANDREW' and us.sequence_name = 'POSTS_SEQ'
D, [2017-01-18T13:37:37.521575 #17739] DEBUG -- :   Primary Key (33.3ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ANDREW' AND c.table_name = 'POSTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2017-01-18T13:37:37.525543 #17739] DEBUG -- :   Primary Key Trigger (3.4ms)            SELECT trigger_name
          FROM all_triggers
          WHERE owner = 'ANDREW'
            AND trigger_name = 'POSTS_PKT'
            AND table_owner = 'ANDREW'
            AND table_name = 'POSTS'
            AND status = 'ENABLED'

D, [2017-01-18T13:37:37.565800 #17739] DEBUG -- :   SQL (27.4ms)  INSERT INTO "POSTS" ("PRICE", "ID") VALUES (:a1, :a2)  [["price", 0.213402e4], ["id", 10000]]
E

Finished in 0.289241s, 3.4573 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_save_record_with_bigdecimal:
ActiveRecord::StatementInvalid: OCIError: ORA-01722: неверное число: INSERT INTO "POSTS" ("PRICE", "ID") VALUES (:a1, :a2)
    stmt.c:243:in oci8lib_240.so
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.3/lib/oci8/cursor.rb:129:in `exec'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:166:in `exec_update'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:120:in `block in exec_insert'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1284:in `log'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-oracle_enhanced-adapter-1.7.9/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:99:in `exec_insert'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:124:in `insert'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/relation.rb:65:in `insert'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:560:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/counter_cache.rb:128:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:302:in `block in _create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:302:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/timestamp.rb:68:in `_create_record'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:540:in `create_or_update'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `block in create_or_update'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:152:in `save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/validations.rb:50:in `save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:324:in `block in save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/transactions.rb:324:in `save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/suppressor.rb:45:in `save!'
    /home/andrew/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.1/lib/active_record/persistence.rb:51:in `create!'
    bug_bigdecimal_save.rb:56:in `test_save_record_with_bigdecimal'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```
May be something wrong with database settings? Are there any dependencies for database settings?

**Comment by yahonda** [comment] 2017-01-18 17:48
It is likely due to the difference of decimal separator character difference between Oracle database and Rails application code. This assumption comes from the error message string "OCIError: ORA-01722: неверное число: ", based on google translate it looks like it is Russian.

In my environment, which test case does not fail, NLS_NUMERIC_CHARACTERS is `.,`.

```sql
SQL> select * from v$nls_parameters
  2  where parameter = 'NLS_NUMERIC_CHARACTERS'
  3  ;

PARAMETER
----------------------------------------------------------------
VALUE                                                                CON_ID
---------------------------------------------------------------- ----------
NLS_NUMERIC_CHARACTERS
.,                                                                        0
```
[NLS_NUMERIC_CHARACTERS](https://docs.oracle.com/database/121/NLSPG/ch3globenv.htm#GUID-F7477179-18DA-445A-AD07-05CD22EEC425)

Here, the first character is decimal separator, the second one is group separator.
This test case value `2134.02` expects that the decimal separator is "." , which needs to be same as the first character of NLS_NUMERIC_CHARACTERS parameter value.

```ruby
 post = Post.create!(price: 2134.02)
```
I assume that NLS_NUMERIC_CHARACTERS has some different value from the above. 

If my assumption is correct setting `  :nls_numeric_characters => ',.'` in your `database.yml` would address this.  

```ruby
CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD,
  :nls_numeric_characters => '.,'
}
```
There would be some other good ways to address this error but I'm not familiar with one where decimal separator is not ".".

**Comment by AgeevAndrew** [comment] 2017-01-18 23:53
Thank you very mauch for your answer!
Now it works.

**Comment by yahonda** [comment] 2017-01-19 02:26
Thanks for the update. Closing it since the original issue have been addressed.

**Closed by yahonda** 2017-01-19 02:26 UTC
