### ISSUE TITLE
disable_referential_integrity error with case-sensitive table names

### ISSUE THREAD

**Issue by bpatram** [rsim/oracle-enhanced#1012] opened 2016-10-13 18:17 UTC
When calling `disable_referential_integrity` the query made does not quote table or constraint names which causes an error for tables and constraints named with a case-sensitive name. 

For example a query to disable constraints now is:
`ALTER TABLE FooBar DISABLE CONSTRAINT FooBar_Foo_FK;`
Which throws a "ORA-00942: table or view does not exist" error from the database

Instead of:
`ALTER TABLE "FooBar" DISABLE CONSTRAINT "FooBar_Foo_FK";`

This affects the follow lines:
https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb#L437-L442

**Comment by yahonda** [comment] 2016-10-14 14:57
Thanks for reporting. Would you update the Gemfile to add this entry and try if it reproduces or not.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'diag1012'
```

This report does not mention Oracle enhanced adapter version used it assumes that it is 1.7.x.

**Comment by yahonda** [comment] 2016-10-14 15:47
#1014 has been merged to master since I was able to reproduce this error by myself.

**Comment by bpatram** [comment] 2016-10-14 16:35
@yahonda Yes, I am using the latest version 1.7.3. This resolves the issue. Thank you for such a fast turn around!

**Comment by yahonda** [comment] 2016-10-14 17:06
Thanks for the update and providing versions you are using. As #1014 has been merged to master then closing this.

**Closed by yahonda** 2016-10-14 17:06 UTC
