### ISSUE TITLE
OCIError: ORA-00904

### ISSUE THREAD

**Issue by Dharshi** [rsim/oracle-enhanced#662] opened 2015-07-04 06:15 UTC
I have done following updates

rails from 4.1.0 to 4.2.3
activerecord-oracle_enhanced-adapter from 1.5.5 to 1.6.0
ruby-oci8 from 2.1.7 to 2.1.8

when I run
bundle exec rake db:schema:load

it results following error
```ruby
add_index("users", ["LOWER(\"USER_ID\")"], {:name=>"index_users_on_lower_user_id", :unique=>true})
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-00904: : invalid identifier: ALTER TABLE "USERS" ADD CONSTRAINT "INDEX_USERS_ON_LOWER_USER_ID" UNIQUE (LOWER("USER_ID"))
stmt.c:250:in oci8lib_220.bundle

/Users/dharshi/.rvm/gems/ruby-2.2.1@iteach/gems/ruby-oci8-2.1.8/lib/oci8/cursor.rb:129:in `exec'
```

**Comment by yahonda** [comment] 2015-07-04 19:41
Looks like it is related with #617. Would you provide the migration definition you are using?

**Comment by Dharshi** [comment] 2015-07-04 23:14
add_index :users, 'lower(user_id)', unique: true, name: :index_users_on_lower_user_id

**Comment by yahonda** [comment] 2015-07-05 14:37
Thanks for the info.
Would you update your Gemfile and see if this issue is resolved or not.
```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'yahonda/oracle-enhanced', branch: 'ora662'
```
If it works, I'm going to open a pull request with some tests.

**Comment by Dharshi** [comment] 2015-07-06 00:29
Thank you!.. it works. Appreciate the quick response.

**Comment by Dharshi** [comment] 2015-07-06 04:20
I came up with another set of errors like following. 

ActiveRecord::StatementInvalid:
       OCIError: ORA-00904: "annual_departments.name": invalid identifier: SELECT annual_departments.name FROM "ANNUAL_DEPARTMENTS" INNER JOIN "YEARS" ON "YEARS"."ID" = "ANNUAL_DEPARTMENTS"."YEAR_ID" INNER JOIN "ORG_UNITS" ON "ORG_UNITS"."ID" = "ANNUAL_DEPARTMENTS"."ORG_UNIT_ID" WHERE (CONTAINS("annual_departments.name", '%xyz%', 0) > 0) AND (years.year = '2015' AND org_units.ancestry_depth = 2)  ORDER BY SCORE(0) DESC, annual_departments.name ASC

**Comment by yahonda** [comment] 2015-07-06 12:23
Thanks for testing #663 has been merged to master. 
Also please open another issue with reproduce case including migration information for both models and rails code which triggers this error. This issue will get locked after it is closed.

**Closed by yahonda** 2015-07-06 12:23 UTC
