### ISSUE TITLE
default_value of a string field is 'N' in the migration. but it is getting stored as 'f'

### ISSUE THREAD

**Issue by lramamoo** [rsim/oracle-enhanced#665] opened 2015-07-09 08:08 UTC
In the migration the default value of a string field is given as 'N'. But on Udf.new the field is getting the value 'f' instead of 'N'. The following is the test case.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.2'
  gem 'activerecord-oracle_enhanced-adapter',:git => 'git://github.com/rsim/oracle-enhanced.git'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: 'oracle_enhanced', database: 'inw')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :udf_tests do |t|
    t.string :select_options, :limit => 1, :default => 'N'
  end
end

class UdfTest < ActiveRecord::Base

end

class BugTest < Minitest::Test
  def test_association_stuff
    udf = UdfTest.new
    udf.save
    udf.reload
    assert_equal udf.select_options, 'N'
  end
end
```

The above test case passes with following gems:

gem 'activerecord', '3.2.13'
gem 'activerecord-oracle_enhanced-adapter', '1.4.2'

**Comment by yahonda** [comment] 2015-07-10 13:31
Thanks for providing a test case. I do not reproduce this error.
Here are log and modified test.rb to make it run in my environment, such as database username. 
I did not change the test code itself.

```ruby
2.2.2@rails42 [~/work/rep665]$ ruby test.rb
Updating git://github.com/rsim/oracle-enhanced.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.2
Using builder 3.2.2
Using activemodel 4.2.2
Using arel 6.0.0
Using activerecord 4.2.2
Using activerecord-oracle_enhanced-adapter 1.6.1 from git://github.com/rsim/oracle-enhanced.git (at master)
Using ruby-oci8 2.1.8
Using bundler 1.10.5
-- create_table(:udf_tests, {:force=>true})
D, [2015-07-10T13:28:34.824977 #1204] DEBUG -- :    (43.0ms)  DROP TABLE "UDF_TESTS"
D, [2015-07-10T13:28:34.831700 #1204] DEBUG -- :    (6.3ms)  DROP SEQUENCE "UDF_TESTS_SEQ"
D, [2015-07-10T13:28:34.845264 #1204] DEBUG -- :    (12.8ms)  CREATE TABLE "UDF_TESTS" ("ID" NUMBER(38) NOT NULL PRIMARY KEY, "SELECT_OPTIONS" VARCHAR2(1) DEFAULT 'N')
D, [2015-07-10T13:28:34.848436 #1204] DEBUG -- :    (2.8ms)  CREATE SEQUENCE "UDF_TESTS_SEQ" START WITH 10000
   -> 0.1287s
Run options: --seed 14779

# Running:

D, [2015-07-10T13:28:34.875426 #1204] DEBUG -- :    (3.6ms)  SELECT column_name AS name, data_type AS sql_type, data_default, nullable, virtual_column, hidden_column, data_type_owner AS sql_type_owner, DECODE(data_type, 'NUMBER', data_precision, 'FLOAT', data_precision, 'VARCHAR2', DECODE(char_used, 'C', char_length, data_length), 'RAW', DECODE(char_used, 'C', char_length, data_length), 'CHAR', DECODE(char_used, 'C', char_length, data_length), NULL) AS limit, DECODE(data_type, 'NUMBER', data_scale, NULL) AS scale FROM all_tab_cols WHERE owner = 'ORACLE_ENHANCED' AND table_name = 'UDF_TESTS' AND hidden_column = 'NO' ORDER BY column_id
D, [2015-07-10T13:28:34.927754 #1204] DEBUG -- :    (51.5ms)  SELECT DECODE(table_name, UPPER(table_name), LOWER(table_name), table_name) FROM all_tables WHERE owner = SYS_CONTEXT('userenv', 'session_user') AND secondary = 'N'
D, [2015-07-10T13:28:34.929157 #1204] DEBUG -- :   Sequence (0.6ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ORACLE_ENHANCED' and us.sequence_name = 'UDF_TESTS_SEQ'
D, [2015-07-10T13:28:34.931629 #1204] DEBUG -- :   Primary Key (2.3ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ORACLE_ENHANCED' AND c.table_name = 'UDF_TESTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2015-07-10T13:28:34.937520 #1204] DEBUG -- :   Sequence (0.6ms)  select us.sequence_name from all_sequences us where us.sequence_owner = 'ORACLE_ENHANCED' and us.sequence_name = 'UDF_TESTS_SEQ'
D, [2015-07-10T13:28:34.938872 #1204] DEBUG -- :   Primary Key (1.1ms)  SELECT cc.column_name FROM all_constraints c, all_cons_columns cc WHERE c.owner = 'ORACLE_ENHANCED' AND c.table_name = 'UDF_TESTS' AND c.constraint_type = 'P' AND cc.owner = c.owner AND cc.constraint_name = c.constraint_name
D, [2015-07-10T13:28:34.940182 #1204] DEBUG -- :   Primary Key Trigger (1.1ms)            SELECT trigger_name
          FROM all_triggers
          WHERE owner = 'ORACLE_ENHANCED'
            AND trigger_name = 'UDF_TESTS_PKT'
            AND table_owner = 'ORACLE_ENHANCED'
            AND table_name = 'UDF_TESTS'
            AND status = 'ENABLED'

D, [2015-07-10T13:28:34.952926 #1204] DEBUG -- :   SQL (7.7ms)  INSERT INTO "UDF_TESTS" ("ID") VALUES (:a1)  [["id", 10000]]
D, [2015-07-10T13:28:34.959620 #1204] DEBUG -- :   UdfTest Load (2.0ms)  SELECT  "UDF_TESTS".* FROM "UDF_TESTS" WHERE "UDF_TESTS"."ID" = :a1 AND ROWNUM <= 1   [["id", 10000]]
.

Finished in 0.091514s, 10.9273 runs/s, 10.9273 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.2'
  gem 'activerecord-oracle_enhanced-adapter',:git => 'git://github.com/rsim/oracle-enhanced.git'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)


DATABASE_NAME         = ENV['DATABASE_NAME']         || 'orcl'
DATABASE_HOST         = ENV['DATABASE_HOST']         || "127.0.0.1"
DATABASE_PORT         = ENV['DATABASE_PORT']         || 1521
DATABASE_USER         = ENV['DATABASE_USER']         || 'oracle_enhanced'
DATABASE_PASSWORD     = ENV['DATABASE_PASSWORD']     || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD
}

ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :udf_tests ,:force => true do |t|
    t.string :select_options, :limit => 1, :default => 'N'
  end
end

class UdfTest < ActiveRecord::Base

end

class BugTest < Minitest::Test
  def test_association_stuff
    udf = UdfTest.new
    udf.save
    udf.reload
    assert_equal udf.select_options, 'N'
  end
end
```

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

**Comment by yahonda** [comment] 2015-10-12 21:00
Closing since no feedback available. Please reopen it it still reproduce with a valid test case.

**Closed by yahonda** 2015-10-12 21:00 UTC
