### ISSUE TITLE
Model.first doesn't work on Rails 5 and Oracle 12c (problem with param binding: ORA-01036)

### ISSUE THREAD

**Issue by Envek** [rsim/oracle-enhanced#833] opened 2016-05-09 16:54 UTC
Hello! Thank you for your work on oracle_enhanced adapter!

Currently I'm trying to upgrade one of my apps from Rails 4.2.6 and oracle-enhanced 1.6.6 to Rails 5.0.0 and oracle-enhanced `rails5` branch.

I'm trying to execute query like any of these on any model:

```ruby
User.find_by(login: 'strela')
User.first
User.first(5)
User.page(2).to_a            # Paging with Kaminari
User.all.to_a.first.employee # associations doesn't work either
```

and getting next error:

```
User Load (0.8ms)  SELECT  "USERS".* FROM "USERS" WHERE "USERS"."LOGIN" = ? FETCH FIRST ? ROWS ONLY  [["login", "strela"], ["LIMIT", 1]]
from stmt.c:195:in oci8lib_230.so
OCIError - ORA-01036: illegal variable name/number:
  ruby-oci8 (2.2.2) lib/oci8/cursor.rb:100:in `bind_param'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:154:in `bind_param'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:126:in `block in bind_params'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced/oci_connection.rb:122:in `bind_params'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:34:in `block in exec_query'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
  activesupport (5.0.0.rc1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:1211:in `log'
   () home/envek/.rvm/gems/ruby-2.3.0/bundler/gems/oracle-enhanced-6628b66600c7/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb:22:in `exec_query'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
  activerecord (5.0.0.rc1) lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
  activerecord (5.0.0.rc1) lib/active_record/querying.rb:39:in `find_by_sql'
  activerecord (5.0.0.rc1) lib/active_record/statement_cache.rb:109:in `execute'
  activerecord (5.0.0.rc1) lib/active_record/core.rb:203:in `find_by'
  app/controllers/application_controller.rb:34:in `authorize_user_by_sudir_header'
  …
```

Ruby: MRI 2.3.0
Rails: 5.0.0.rc1
oracle-enhanced: `rails5` branch @ 6628b66600c7 (today's latest)
Oracle: 12c from https://github.com/MaksymBilenko/docker-oracle-12c
OS: Ubuntu 16.04 (client libs installed by this manual: https://help.ubuntu.com/community/Oracle%20Instant%20Client )

P.S> I'm very glad to see support of the `OFFSET ? ROWS FETCH FIRST ? ROWS ONLY` syntax! Thank you!

**Comment by yahonda** [comment] 2016-05-09 18:08
I think this is duplicate of https://github.com/rails/arel/pull/422 .
It has been merged to Arel master branch already, but not backported to v7.0.x yet.

Please update your Gemfile to use patched version of Arel.
```ruby
gem 'arel', github: 'yahonda/arel', branch: 'v700_oracle12'
```

**Comment by Envek** [comment] 2016-05-09 18:54
Yes, it works on patched version of Arel, thank you!

Waiting for backport of rails/arel#422 and rails/arel#430 then.

**Comment by yahonda** [comment] 2016-05-09 18:58
Thanks for the confirmation. Closing this issue since releasing newer version of Arel is (at least) out of my control. I have just requested it today, it would take some time maybe.

**Closed by yahonda** 2016-05-09 18:58 UTC

**Comment by yahonda** [comment] 2016-07-20 01:35
FYI. Are 7.1.0 has been released.
