### ISSUE TITLE
Random OCIErrors because of wrong NLS settings

### ISSUE THREAD

**Issue by volkit** [rsim/oracle-enhanced#1717] opened 2018-04-27 15:12 UTC
Our DB randomly throws OCIErrors ORA-01843 and ORA-01861. Sometimes these errors don't occur for days, sometimes they occur on every request. The problem seems to be that the NLS settings change randomly. As you can see in the log file, the timestamp format for the first session is DD.MM.RR HH24:MI:SSXFF (results in error) and for the second session, an hour later, YYYY-MM-DD HH24:MI:SS:FF6 (no error).

In tried to set these NLS parameters in database.yml, but it didn't help:

nls_timestamp_format: 'YYYY-MM-DD HH24:MI:SS:FF6'
nls_date_format: 'YYYY-MM-DD HH24:MI:SS'
nls_numeric_characters: ',.'

System config:
CentOS 7 with env var NLS_LANG=GERMAN_GERMANY.WE8MSWIN1252 
oracle-instantclient11.2
rails (5.1.5)
activerecord-oracle_enhanced-adapter (1.8.2)
ruby-oci8 (2.2.5.1)
puma (3.11.2) with 4 worker processes
oracle 11.2.0.3.0

Maybe the env var is randomly consumed by oracle_enhanced or some worker processess don't recognize the nls parameters in database.yml? 

Until now I couldn't reproduce this error in development, so no test case. It only happens sometimes in production.

[OCIError.log](https://github.com/rsim/oracle-enhanced/files/1955623/OCIError.log)

**Comment by yahonda** [comment] 2018-04-30 22:45
Hi, 

I'd like you to provide the test case to reproduce it. In the mean time, would you provide the table definition of `USERSHELLS`?  I'd like to know if `LASTLOGIN`, `UPDATED_AT` column types are `DATE` or `TIMESTAMP`.

```ruby
D, [2018-04-27T06:38:23.259152 #20616] DEBUG -- : [0e743178-399a-463c-b466-5ad12099db46]   [1m[35mSQL (1933.2ms)[0m  [1m[33mUPDATE "USERSHELLS" SET "LASTLOGIN" = :a1, "UPDATED_AT" = :a2 WHERE "USERSHELLS"."ID" = :a3[0m  [["lastlogin", "2018-04-27 06:38:21.321952"], ["updated_at", "2018-04-27 06:38:21.323404"], ["id", 10077]]
I, [2018-04-27T06:38:23.261450 #20616]  INFO -- : [0e743178-399a-463c-b466-5ad12099db46] Completed 500 Internal Server Error in 938179ms (ActiveRecord: 2006.4ms)
F, [2018-04-27T06:38:23.264220 #20616] FATAL -- : [0e743178-399a-463c-b466-5ad12099db46]   
F, [2018-04-27T06:38:23.264380 #20616] FATAL -- : [0e743178-399a-463c-b466-5ad12099db46] ActiveRecord::StatementInvalid (OCIError: ORA-01843: Kein gültiger Monat: UPDATE "USERSHELLS" SET "LASTLOGIN" = :a1, "UPDATED_AT" = :a2 WHERE "USERSHELLS"."ID" = :a3):
```

Thanks you.

**Comment by patrickwilkes** [comment] 2018-05-02 02:43
We've also seen the same ORA-01843 error, twice in production for one particular application in the last week. The application was recently upgraded to Rails 5.1, and the problems have started since then. It hasn't happened in other environments, and it hasn't happened for another Rails 5.1.4 application that we have. No clue how to reproduce it at this stage ...

The application runs on two servers, and both servers started having the same error around the same time. A restart of the app resolved it and it ran for several days without a problem between the two incidents.

The error for us happens on the SESSIONS table
``
OCIError: ORA-01843: not a valid month:
 INSERT INTO "SESSIONS" ("SESSION_ID", "DATA", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5)
``

CREATED_AT and UPDATED_AT were redefined in a migration for the Rails 5.1 upgrade as :datetime columns which changed them to TIMESTAMP(6).
``
change_column(:sessions, :created_at, :datetime)
change_column(:sessions, :updated_at, :datetime)
``

Setup is very similar to @volkit.

RHEL 7.4
Ruby 2.4.4
NLS_LANG AMERICAN.AL32UTF8 (otherwise no NLS settings)
oracle-instantclient11.2 (actually 11.2.0.4.0-1)
Rails (5.1.5)
activerecord-oracle_enhanced-adapter (1.8.2)
ruby-oci8 (2.2.5.1)
Phusion Passenger (5.0.30)
Oracle 11.1.0.7.0

**Comment by volkit** [comment] 2018-05-07 07:57
Nothing special, maybe a database logon trigger can do the same:

```
  before_action :set_nls

  private
  def set_nls
    settings = %q[ ALTER SESSION set nls_timestamp_format='YYYY-MM-DD HH24:MI:SS:FF6' nls_date_format='YYYY-MM-DD HH24:MI:SS' nls_numeric_characters=',.']
    ActiveRecord::Base.connection.execute(settings)
  end
```

**Comment by patrickwilkes** [comment] 2018-05-08 01:17
We are no closer to finding the cause of the errors, but we have some more information on what is happening:

1. the problem is only happening in our DMZ environment - we have two apps running internally with the same activerecord-oracle_enhanced-adapter and ruby-oci8 versions with no problems.
1. there are two other apps in the same DMZ environment that also have no problems - they are Rails 3 apps with activerecord-oracle_enhanced-adapter (1.4.3) and ruby-oci8 (2.2.2).
1. the application with the problem runs on two servers, sometimes both servers are affected at the same time, sometimes just one.
1. once the errors start they can only be fixed with an application restart
1. in the last 12 days the problem has occurred four times on one server and twice on the second server
1. the errors always start at the same time of day
1. every time the errors start a request completed within the previous one minute with no problem
1. on the first error there is often a delay of around 15 seconds between the request starting and the error being thrown, here's an example from the logs:

```
I, [2018-05-07T06:03:19.364263 #15432]  INFO -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d] Started GET "/asup/" for x.x.x.x at 2018-05-07 06:03:19 +1200
I, [2018-05-07T06:03:19.365729 #15432]  INFO -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d] Processing by AsupApplicationsController#start as */*
I, [2018-05-07T06:03:19.379712 #15432]  INFO -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d] Redirected to https://some.domain/asup/enquiry
I, [2018-05-07T06:03:19.380113 #15432]  INFO -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d] Completed 302 Found in 14ms (ActiveRecord: 3.2ms)
D, [2018-05-07T06:03:19.387419 #15432] DEBUG -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d]   [1m[35mSQL (1.1ms)[0m  [1m[33mUPDATE "SESSIONS" SET "DATA" = :a1, "UPDATED_AT" = :a2 WHERE "SESSIONS"."ID" = :a3[0m  [["data", #<OCI8::CLOB:0x000055836a0b8a40>], ["updated_at", "2018-05-07 06:03:19.384051"], ["id", 1165392]]
D, [2018-05-07T06:03:19.390119 #15432] DEBUG -- : [0622df9e-7219-4dd9-87ac-ae17dfc9495d]   [1m[36mWritable Large Object (1.9ms)[0m  [1m[37mSELECT "DATA" FROM "SESSIONS" WHERE "ID" = 1165392 FOR UPDATE[0m

I, [2018-05-07T06:04:19.288565 #15432]  INFO -- : [3b3fa279-e127-4ddc-b8b9-95a7b75bb4c4] Started GET "/asup/" for x.x.x.x at 2018-05-07 06:04:19 +1200
I, [2018-05-07T06:04:19.290156 #15432]  INFO -- : [3b3fa279-e127-4ddc-b8b9-95a7b75bb4c4] Processing by AsupApplicationsController#start as */*
E, [2018-05-07T06:04:35.432962 #15432] ERROR -- : [3b3fa279-e127-4ddc-b8b9-95a7b75bb4c4] OCIError: ORA-01843: not a valid month: INSERT INTO "SESSIONS" ("SESSION_ID", "DATA", "CREATED_AT", "UPDATED_AT", "ID") VALUES (:a1, :a2, :a3, :a4, :a5)
```

We are deploying the same workaround as @volkit today. 

I will attempt to find out what is happening in our environment at the time the errors start.

**Comment by yahonda** [comment] 2018-05-10 23:00
Thanks for the update @volkit .

Starting from Rails 6, `nls_date_format` will be set to "YYYY-MM-DD HH24:MI:SS" and `nls_timestamp_format` will be set to "YYYY-MM-DD HH24:MI:SS:FF6" by default. Refer #1685
For `NLS_NUMERIC_CHARACTERS`, there was a discussion #109 . I am thinking about setting `NLS_NUMERIC_CHARACTERS` to `.,` by default.

**Closed** 2018-07-17 00:02 UTC
Labels: wontfix
