### ISSUE TITLE
Dumping SDO_GEOMETRY columns in db/schema.rb

### ISSUE THREAD

**Issue by Envek** [rsim/oracle-enhanced#749] opened 2015-12-08 13:03 UTC
Hello. Thank you for oracle_enhanced, it's very useful and reduces pain with working with oracle in order of magnitudes.

I've created `SDO_GEOMETRY` column, but it doesn't getting dumped in `db/schema.rb`.

My migration is:

```ruby
class AddServiceAreaShapeToOus < ActiveRecord::Migration
  def change
    add_column :ous, :service_area_shape, :sdo_geometry

    reversible do |direction|
      direction.up do
        execute <<-SQL.strip_heredoc
          INSERT INTO USER_SDO_GEOM_METADATA (
            TABLE_NAME,
            COLUMN_NAME,
            DIMINFO,
            SRID
          )
          SELECT
            'OUS',
            'SERVICE_AREA_SHAPE',
            SDO_DIM_ARRAY(
              SDO_DIM_ELEMENT('X', -85, 85, 0.005),
              SDO_DIM_ELEMENT('Y', -180, 180, 0.005)),
            NULL
          FROM DUAL
          WHERE NOT EXISTS(
            SELECT * FROM USER_SDO_GEOM_METADATA
            WHERE
              TABLE_NAME = 'OUS'
              AND COLUMN_NAME = 'SERVICE_AREA_SHAPE'
          )
        SQL

        execute <<-SQL.strip_heredoc
          CREATE INDEX ous_shape_spatial_index
            ON ous(service_area_shape)
            INDEXTYPE IS MDSYS.SPATIAL_INDEX
        SQL
      end

      direction.down do
        execute <<-SQL.strip_heredoc
          DROP INDEX ous_shape_spatial_index
        SQL

        execute <<-SQL.strip_heredoc
          DELETE FROM USER_SDO_GEOM_METADATA
          WHERE
            TABLE_NAME = 'OUS'
            AND COLUMN_NAME = 'SERVICE_AREA_SHAPE'
        SQL
      end
    end

  end
end
```

And I getting in `db/schema.rb` following:

```ruby
# Could not dump table "ous" because of following StandardError
#   Unknown type 'PUBLIC.SDO_GEOMETRY' for column 'service_area_shape'
```

I expecting that new column and index will be dumped into schema.

I'm using the latest versions of ruby-oci8 (2.2.1) and activerecord-oracle_enhanced-adapter (1.6.5) against Oracle 12c with deinstalled Spatial and Graph using this manual: https://docs.oracle.com/database/121/SPATL/sdo_locator.htm#SPATL1433 (so only Locator is available)

Am I doing something wrong? Any additional info I should provide?

With best regards, Andrey Novikov.

**Comment by yahonda** [comment] 2015-12-08 18:36
Unfortunately Oracle enhanced adapter does not implement `SDO_GEOMETRY` object type then it is an expected behavior that you get this 'Unknown type'.

**Comment by yahonda** [comment] 2016-01-25 19:47
Closing this since it does not implement `SDO_GEOMETRY`. If anyone are interested in this feature pull requests are welcomed.

**Closed by yahonda** 2016-01-25 19:47 UTC
