### ISSUE TITLE
no implicit conversion of nil into Integer error on transaction

### ISSUE THREAD

**Issue by vnmjacky** [rsim/oracle-enhanced#427] opened 2014-03-09 03:08 UTC
When i do transactions get the error: no implicit conversion of nil into Integer.

Im using:

         begin
              ActiveRecord::Base.transaction do

              end
         end

**Comment by yahonda** [comment] 2016-01-25 20:23
Would you create a minimum test case to reproduce it.

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  #gem 'activerecord', '4.2.5'
  gem 'activerecord-oracle_enhanced-adapter', '1.6.6'
  gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'master'
  gem 'ruby-oci8'
  gem 'minitest'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'active_record/connection_adapters/oracle_enhanced_adapter'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# Set Oracle enhanced adapter specific connection parameters
DATABASE_NAME = ENV['DATABASE_NAME'] || 'orcl'
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']
DATABASE_USER = ENV['DATABASE_USER'] || 'oracle_enhanced'
DATABASE_PASSWORD = ENV['DATABASE_PASSWORD'] || 'oracle_enhanced'
DATABASE_SYS_PASSWORD = ENV['DATABASE_SYS_PASSWORD'] || 'admin'

CONNECTION_PARAMS = {
  :adapter => "oracle_enhanced",
  :database => DATABASE_NAME,
  :host => DATABASE_HOST,
  :port => DATABASE_PORT,
  :username => DATABASE_USER,
  :password => DATABASE_PASSWORD,
  :prepared_statements => false
}

#ActiveRecord::Base.default_timezone = :local
ActiveRecord::Base.default_timezone = :utc
ActiveRecord::Base.establish_connection(CONNECTION_PARAMS)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.timestamps null: false
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_find_by_created_at
    post = Post.create!

    created_at = post.created_at

    assert_equal post, Post.find_by(created_at: created_at)
  end
end
```

Thanks.

**Comment by yahonda** [comment] 2016-08-01 21:39
Closing due to no updates. Please provide a test case or detailed information it it needs reopen.

**Closed by yahonda** 2016-08-01 21:39 UTC
