### ISSUE TITLE
Infinite loop in indexes_with_oracle_enhanced and Rails 4.2.0

### ISSUE THREAD

**Issue by lanusau** [rsim/oracle-enhanced#535] opened 2015-01-12 19:48 UTC
I am testing upgrade to Rails 4.2.0 using oracle-enhanced@rails42 branch. This application is unusual in that it uses multiple database connections (mysql and oracle) and mysql2 adapter is specified for test/development/production entries in database.env and that is the only schema we want  do dump when executing db:schema:dump. 
It used to work fine with Rails 4.0.x and activerecord-oracle_enhanced_adapter 1.5. But now when running db:schema:dump "SystemStackError: stack level too deep" exception is thrown. Its happening in "indexes_with_oracle_enhanced" method, where it calls "indexes_without_oracle_enhanced(table, stream)" but that invokes "indexes_with_oracle_enhanced" again in infinite loop overflowing stack. 

I temporarily fixed it by commenting out inclusion of ActiveRecord::ConnectionAdapters::OracleEnhancedSchemaDumper into ActiveRecord::SchemaDumper, since I don't need to dump schema from Oracle database. 

I guess probability to hit this bug is somewhat low as you'd need this unusual setup where oracle-enhanced adapter is used by database to be dumped is MySQL. 

Limus

**Comment by garyharan** [comment] 2015-02-26 14:24
I'm having the same issue.  Commenting out the inclusion works for me as well since my scenario also forgoes the need to dump the oracle DB.  It would be nice to have more control over this.

**Comment by yahonda** [comment] 2015-03-02 01:02
Thanks for your reports. Would you try to reproduce using the master branch.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'master'  
```
If you still reproduce it, there should be something wrong with these logic to see if it uses Oracle enhanced adapter or not.

https://github.com/rsim/oracle-enhanced/blob/master/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb#L108-L112

**Comment by lanusau** [comment] 2015-03-02 17:35
@yahonda  - yes, seems that its fixed in master branch. Looks like the problem in rails42 branch is here:

https://github.com/rsim/oracle-enhanced/blob/rails42/lib/active_record/connection_adapters/oracle_enhanced_schema_dumper.rb#L9-L10

"alias_method_chain" is called 2 times for :indexes

**Comment by yahonda** [comment] 2015-03-03 13:52
Thanks for the update. #560 has been merged to `rails42`.

**Comment by yahonda** [comment] 2015-03-03 13:54
@lanusau @garyharan Would you try to see if it reproduces using the latest rails42 branch.

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails42' 
```

**Comment by garyharan** [comment] 2015-03-03 13:56
My Oracle installation is offline now and we've moved to PG :-(

Thanks for the help though!  On the next app I use Oracle this will come in handy.

**Comment by yahonda** [comment] 2015-03-03 13:57
@garyharan Thanks for the reporting. PostgreSQL is also a good database, I think.

**Comment by lanusau** [comment] 2015-03-03 16:20
@yahonda - rails42 branch works fine now. Any idea when this can be cut into a new gem ?

**Comment by yahonda** [comment] 2015-03-03 20:28
Closing because it is fixed in rails42 branch.

@lanusau Thanks for testing, so far I do not say when we can release the oracle enhanced adapter gem which supports Rails 4.2 since there are some showstopper issues reported i.e. #546.

**Closed by yahonda** 2015-03-03 20:28 UTC
