### ISSUE TITLE
emulate_booleans_from_strings takes priority over attribute api

### ISSUE THREAD

**Issue by bardbess** [rsim/oracle-enhanced#1621] opened 2018-01-05 03:49 UTC
### Steps to reproduce

Set `emulate_booleans_from_strings = true` and change the column type in the model. This occurs on `release17`,`release18` and master branch.
Test case for minitest:

```
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.emulate_booleans_from_strings = true

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.string  :str_column_ind, limit: 1
  end
end

class Post < ActiveRecord::Base
  attribute :str_column_ind, :string
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal :string, Post.columns_hash['str_column_ind'].type
  end
end
```

### Expected behavior
The column type should be set to `:string` and the value returned should be a `String`

### Actual behavior
The column type is `:boolean` but the value from the column is correct (`String`)

### System configuration
**Rails version**: 5.0.6, 5.1.4, 5.2.0.beta2

**Oracle enhanced adapter version**: 1.7.11, 1.8.2, 5.2.0.beta1

**Ruby version**: 2.2.2, 2.2.7

**Oracle Database version**: 11g release 11.2.0.1.0

**Comment by yahonda** [comment] 2018-01-06 04:06
Thanks for providing a test case to reproduce it.

 Would you give it a try by updating `Gemfile` as follows. This branch is for Rails 5.2.0.beta2.

 ```ruby
 gem "activerecord-oracle_enhanced-adapter",  github: "yahonda/oracle-enhanced", branch: "diag1621"
 ```

If you would like to test with other versions of Rails, you can refer this commit.
 https://github.com/yahonda/oracle-enhanced/commit/05776847eb9bb033f6497e0e8d1437df95d190a7

Note: If this commit addresses #1621 it will be available only for Oracle enhanced adapter 5.2.
since this commit changes the behavior of `emulate_booleans_from_strings` then it will not be
backported to `release18` branch or older version of Oracle enhanced adapter.

**Comment by bardbess** [comment] 2018-01-07 20:23
Your change is working fine for Rails 5.2.0.beta2. This is not an issue in `release16` and earlier, should it not be considered a bug in `release17` and `release18` and be fixed in the supported version of this gem?

**Comment by bardbess** [comment] 2018-01-07 21:52
On `release17` I am unable to proceed. If I set `emulate_booleans_from_strings = false` then my column type is `:string` when I'm expecting `:boolean` - attribute API is not honoured.

```
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.emulate_booleans_from_strings = false

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.string  :str_column_ind, limit: 1
  end
end

class Post < ActiveRecord::Base
  attribute :str_column_ind, :boolean
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal :boolean, Post.columns_hash['str_column_ind'].type
  end
end
```

If I set `emulate_booleans_from_strings = true` then attribute API is not honoured and my column type is still set to `:boolean` when I'm expecting `:string`.

```
ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.emulate_booleans_from_strings = true

ActiveRecord::Schema.define do
  create_table :posts, :force => true do |t|
    t.string  :str_column_ind, limit: 1
  end
end

class Post < ActiveRecord::Base
  attribute :str_column_ind, :string
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_equal :string, Post.columns_hash['str_column_ind'].type
  end
end
```

**Comment by yahonda** [comment] 2018-01-08 17:26
Thanks for the validation.

#1623 has been merged to master then it will be available for Rails 5.2.

#1623 includes a change for the `boolean_spec.rb`, whic explains this is a spec change for Rails 5.2. 
Then should not be backported to release18 or older versions of Oracle enhanced adapter.

https://github.com/rsim/oracle-enhanced/blob/48b04ded21cfe292f5b7d054af3164652752626d/spec/active_record/oracle_enhanced/type/boolean_spec.rb#L193

For two test cases in the second update:

1. `emulate_booleans_from_strings = false` and `attribute :boolean` for string (VARCHAR2(1) sql type)
This combination should not work. Using string as attribute needs emulate_booleans_from_strings = true

2. `emulate_booleans_from_strings = true` and `attribute :string` 
This combination should work in Rails 5.2 since #1623

Thanks.

**Comment by bardbess** [comment] 2018-01-08 22:12
I may have some more feedback for you once I reach Rails 5.2, I appreciate your time. 

I have [a fix for release17 here](https://github.com/bardbess/oracle-enhanced/commit/8e66a8fb3ac54c6961521609d954de28ea08aa5c) to change `emulate_booleans_from_strings` to behave like rails AR attributes if anyone comes looking, that seemed the most reliable behaviour -  but does leave `emulate_booleans` on `number(1)` open for debate.

You want might consider this for the `master` branch.

**Comment by yahonda** [comment] 2018-01-09 16:26
Thanks for the update.

I have taken a look at https://github.com/bardbess/oracle-enhanced/commit/8e66a8fb3ac54c6961521609d954de28ea08aa5c commit. 

Still I do not think the combination of `emulate_booleans_from_strings = false` and `attribute :<attr_name>, :boolean` is an expected behavior.  However, you can create your own attribute API using `StringBoolean` class. This is one of the benefit of attribute API, not only database adapter but each application can define its own attributes. I'd suggest you to use your own type based on your requirements.

Thank you.

**Closed** 2018-03-17 18:09 UTC
Labels: wontfix
